### PR TITLE
Remove default behaviour of FREERTOS_HEAP.

### PR DESCRIPTION
**Pull request by conara**
To build a complete static application (configSUPPORT_DYNAMIC_ALLOCATION set to 0) an ugly workaround is necessary. When FREERTOS_HEAP (CMake variable) is not set, heap 4 is automatically selected in the current CMake. Without this change I got the following error:

`/home/boris/workspace/base/external/freertos/portable/MemMang/heap_4.c:51:6: error: #error This file must not be used if configSUPPORT_DYNAMIC_ALLOCATION is 0
   51 |     #error This file must not be used if configSUPPORT_DYNAMIC_ALLOCATION is 0`

For additional context, please read: https://forums.freertos.org/t/i-cannot-build-a-complete-static-application-bug-or-feature/9553

-----------
I opted to modify the default behavior of the FREERTOS_HEAP CMake variable because I believe it's essential for the user to be conscious of the chosen heap implementation. While another option was to introduce a magic variable to prevent automatic heap implementation selection, I find this approach to be the most straightforward and logical one.

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jputcu** [comment]
I'm facing the same issue. Found some older related tickets: #594 and #595

**Comment by archigup** [comment]
Hey, thanks for the PR! We're discussing what the best way to solve this issue is, and will get back to you.

**Comment by conara** [comment]
> Hey, thanks for the PR! We're discussing what the best way to solve this issue is, and will get back to you.

Can you give me an update on this point?

**Comment by ActoryOu** [comment]
Hi @conara,
Sorry for late response. We'll get on this by next Friday.

Thanks.

**Review by aggarg — APPROVED** [review]

**Review by ActoryOu — APPROVED** [review]

**Pull request merged**
