### PR TITLE
Support configurable RISC-V chip extension

### PR DESCRIPTION
**Pull request by JoeBenczarski**
Support configurable RISC-V chip extension with cmake

Description
-----------
In this PR:
* Added the **FREERTOS_RISCV_EXTENSION** option along with two port target **GCC_RISC_V_GENERIC** and **IAR_RISC_V_GENERIC**  to allow the user to select which chip extension they want included.
* Move the change to port cmake file to keep the root cmake file clean.
* Developers use existing RISC-V ports with cmake won't have be effected

Existing RISC-V cmake port only support the following combinations:
* FREERTOS_PORT = GCC_RISC_V, chip extension = RISCV_MTIME_CLINT_no_extensions
* FREERTOS_PORT = GCC_RISC_V_PULPINO_VEGA_RV32M1RM, chip extension = Pulpino_Vega_RV32M1RM
* FREERTOS_PORT = IAR_RISC_V, chip extension = RV32I_CLINT_no_extensions

To support other combinations, two generic port targets are created:
* FREERTOS_PORT = GCC_RISC_V_GENERIC
* FREERTOS_PORT = IAR_RISC_V_GENERIC

User has to specify FREERTOS_RISCV_EXTENSION in the cmake file to use these ports:
```
set( FREERTOS_PORT "GCC_RISC_V_GENERIC" CACHE STRING "" FORCE)
set( FREERTOS_RISCV_EXTENSION RISCV_MTIME_CLINT_no_extensions CACHE STRING "" FORCE )
```

Test Steps
-----------
n/a

Checklist:
----------
- [x] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------
#772 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kar-rahul-aws** [comment]
Hi @JoeBenczarski 
Thank you for your valuable contribution. We will review the PR and get back to you.

**Comment by chinglee-iot** [comment]
@JoeBenczarski 
Thank your for creating this PR.
It looks like the change will break existing rics-v project with cmake.
Suggest we create two new ports for `FREERTOS_CHIP_EXTENSION`
* GCC_RISC_V_GENERIC
* IAR_RISC_V_GENERIC 

Please help to take a look at this [PR] suggestion(https://github.com/JoeBenczarski/FreeRTOS-Kernel/pull/1)

**Comment by JoeBenczarski** [comment]
> @JoeBenczarski Thank your for creating this PR. It looks like the change will break existing rics-v project with cmake. Suggest we create two new ports for `FREERTOS_CHIP_EXTENSION`
> 
> * GCC_RISC_V_GENERIC
> * IAR_RISC_V_GENERIC
> 
> Please help to take a look at this [PR] suggestion([JoeBenczarski#1](https://github.com/JoeBenczarski/FreeRTOS-Kernel/pull/1))

Good idea. I just merged that PR.

**Review by chinglee-iot — APPROVED** [review]

**Comment by chinglee-iot** [comment]
> > @JoeBenczarski Thank your for creating this PR. It looks like the change will break existing rics-v project with cmake. Suggest we create two new ports for `FREERTOS_CHIP_EXTENSION`
> > 
> > * GCC_RISC_V_GENERIC
> > * IAR_RISC_V_GENERIC
> > 
> > Please help to take a look at this [PR] suggestion([JoeBenczarski#1](https://github.com/JoeBenczarski/FreeRTOS-Kernel/pull/1))
> 
> Good idea. I just merged that PR.

Thank you. I will also update the description of this PR and ask for another reviewer's opinion.

**Review by AniruddhaKanhere — APPROVED** [review]

**Pull request merged**
