### PR TITLE
Fix prvSelectHighestPriorityTask ready list iteration

### LINKED ISSUE #990: [BUG] SMP prvSelectHighestPriorityTask adds current task to the front of the ready list if pxIndex points to the head of the list
**Describe the bug**
The new implementation for `prvSelectHighestPriorityTask` for SMP uses `vListInsertEnd` to insert the current TCB to the end of the ready task list. `vListInsertEnd` doesn't actually insert an element to the end of a list-- it only adds it such that it is the last element returned by calling `listGET_OWNER_OF_NEXT_ENTRY` multiple times before it starts repeating. Effectively `vListInsertEnd` inserts the node right before the current `pxIndex` node of the list.

In testing with a personal project and stepping through debugging, at first the `pxIndex` of the ready list seems to be the tail element of the list (before the `xListEnd` element). Over time, however, as tasks are removed and added to the ready list, it looks like the `pxIndex` element migrates to the top of the list. Once it reaches the top of the list, `vListInsertEnd` actually ends up inserting the current task TCB node to the front of the ready list!

The fix would be to use listGET_OWNER_OF_NEXT_ENTRY to iterate through the list, instead of starting from the head element.

**Target**
- Development board: Raspberry Pi Pico W (rp2040)
- Instruction Set Architecture: ARM Cortex-M0+
- IDE and version: pico-sdk, ninja, vim, cmake, crossdev generated arm-none-eabi-gcc
- Toolchain and version: arm-none-eabi-gcc (Gentoo 13.2.1_p20240113-r1 p12) 13.2.1 20240113

**Host**
- Host OS: Gentoo Linux
- Version: Unstable (rolling release), kernel version 6.7.0

**To Reproduce**
I don't have a generic reproducer, since it strongly depends on scheduler and task interaction. Even reproducing it on my device is almost like trying to reproduce a race condition, and any slowdown from gdb conditionals renders the issue impossible to reproduce.

My project is set up to mock an HID USB device using Tinyusb. I have a task dedicated to USB handling, a CLI task, a task mocking controller input, and a watchdog task. By dumping the list of active tasks, it looks like the pico-sdk also has a few other tasks running in the background:
```
Tasks active: 7
  task name: prb_cli
  task name: usb
  task name: IDLE1
  task name: IDLE0
  task name: prb_watchdog
  task name: controller
  task name: Tmr Svc
```

I configured all 4 of my tasks to have a core affinity so they only use core 2.

I triggered the issue by constantly requesting the CLI task to output my debug status info using `uxTaskGetSystemState` to get the system state. It can take seconds to almost a minute of me spamming requests (as a human, typing `s` and `enter` to trigger the CLI output) to trigger the bug.

What I observe is that the scheduler consistently schedules the current task once the bug is triggered, starving all others. Makes sense if `pxIndex` is the head node of the ready list, as the current task node gets added before the `pxIndex` node... becoming the new head node.

**Expected behavior**
No resource starvation on the core the bug triggers in.

**Screenshots**
N/A

**Additional context**

See this [FreeRTOS forum post](https://forums.freertos.org/t/bug-prvselecthighestprioritytask-leads-to-same-task-being-scheduled-due-to-vlistinsertend-inserting-to-the-head-of-the-list-not-the-actual-end/19165/7) for a discussion and all of my findings about the issue.

I can open a pull request with an attempted fix, but I have no idea how to go about  preparing unit tests and coverage, or how to do proper regression testing with FreeRTOS.

### PR DESCRIPTION
**Pull request by gemarcano**
Fix prvSelectHighestPriorityTask ready list iteration. Fixes #990.

Description
-----------
Use listGET_OWNER_OF_NEXT_ENTRY to iterate through the ready task list instead of iterating from the head of the list. The SMP changes to prvSelectHighestPriorityTask added the use of vListInsertEnd to append the current task to the end of the list. vListInsertEnd, however, appends a node such that, when using listGET_OWNER_OF_NEXT_ENTRY, it is the last node returned, but it isn't inserted at the actual tail of the list. This led to a case where the list's `pxIndex` eventually managed to become the head of the list, and using `vListInsertEnd` would cause the added node to be added to the head of the list.

Test Steps
-----------
This is not very deterministic to reproduce, but I had around 7 tasks being scheduled, and many of them were sleeping for different amounts of time. The main cause seems to be the `pxIndex` of the ready lists moving to the front of the list.

Checklist:
----------
- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------
#990

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by gemarcano** [comment]
I'm not sure how to go about running regression tests and/or how to write unit tests for this, but I'd be happy to try if pointed in the right direction. The problem is I'm not sure how to reproduce the original issue reliably.

**Comment by rawalexe** [comment]
Thank you for your contribution, we are working towards reviewing your PR.

**Comment by gemarcano** [comment]
I noticed the failed formatting and warning checks-- I've gone ahead and updated the commit to address the errors found by the CI pipeline. If it fails a second time, I'll again update the commit.

**Comment by aggarg** [comment]
Thank you for raising the PR. We are looking at it and will get back to you.

**Comment by gemarcano** [comment]
I saw that a unit test failed, something about calling some length function more than expected. Another alternative solution would be to introduce a new macro/function that appends a node to the actual end of the list (say, at the position before `xListEnd`), and use that instead of `vListInsertEnd`. That wouldn't require modifying the current loop.

**Comment by chinglee-iot** [comment]
@gemarcano 
Thank you for creating this PR. I will look into this PR and the unit test problem. It probably takes some time to look into the detail to discuss with you.

**Comment by aggarg** [comment]
We are currently evaluating another fix - https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1000.

**Comment by chinglee-iot** [comment]
#1000 to address the same issue is merged. This PR will be closed. Thank you for reporting this issue and creating this PR.

**Pull request closed without merging**
