### PR TITLE
Update version number

### PR DESCRIPTION
**Pull request by paulbartell**
Description
-----------
Update the reported version number on the main branch

Test Steps
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by ericbj29 — APPROVED** [review]

**Comment by kstribrnAmzn** [comment]
Let's update the manifest.yml value too then

**Comment by paulbartell** [comment]
> Let's update the manifest.yml value too then

Updated!

**Review by ericbj29 — APPROVED** [review]

**Comment by kstribrnAmzn** [comment]
Can you try running the [manifest verifier](https://github.com/FreeRTOS/CI-CD-Github-Actions/tree/main/manifest-verifier) script on this change? If it passed then I'll be happy.

**Comment by paulbartell** [comment]
> Can you try running the [manifest verifier](https://github.com/FreeRTOS/CI-CD-Github-Actions/tree/main/manifest-verifier) script on this change? If it passed then I'll be happy.

It runs as part of the CI for this repo. Here's the output from running it locally:
```
% python3 manifest-verifier.py --repo-root-path ./
INFO - PARSING manifest.yml FILE: /redacted/FreeRTOS/FreeRTOS/Source
INFO - No dependencies in /redacted/FreeRTOS/FreeRTOS/Source/manifest.yml. Exiting 
```

**Review by Skptak — APPROVED** [review]

**Review by aggarg — APPROVED** [review]

**Pull request merged**
