### PR TITLE
Revert Portable/MikroC Formatting

### PR DESCRIPTION
**Pull request by Skptak**
Description
-----------
Revert PR #768 on MikroC ports

Test Steps
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by htibosch** [comment]
Hello @Skptak, if it doesn't take too much effort, it would be great if you can explain the reasons why you are creating this PR and other recent PRs.

People like me are wasting time opening the page "File changed" in order to discover if anything essential was changed.

It looks like you're raising a series of PR's that are reverting changes. But please put a link or copy/paste a short text.

**Comment by Skptak** [comment]
> Hello @Skptak, if it doesn't take too much effort, it would be great if you can explain the reasons why you are creating this PR and other recent PRs.
> 
> People like me are wasting time opening the page "File changed" in order to discover if anything essential was changed.
> 
> It looks like you're raising a series of PR's that are reverting changes. But please put a link or copy/paste a short text.

Hey @htibosch ,this set of PRs for reverting #768 is being done as we cannot determine if the whitespace changes made in the port files cause compilation errors or not. As we cannot determine if these are breaking changes or not the decision was mde to simply revert all formatting changes in the portable directory.

**Comment by htibosch** [comment]
> Hey @htibosch ,this set of PRs for reverting #768 is being done as we cannot determine if the whitespace changes made in the port files cause compilation errors or not. As we cannot determine if these are breaking changes or not the decision was mde to simply revert all formatting changes in the portable directory.

Ok, thank you for the clear explanation :-)

**Review by chinglee-iot — APPROVED** [review]
Compared with commit before #768 
d6bccb1f4 | 2023-09-05 | Gaurav-Aggarwal-AWS | Fix heap address calculation issue (#781)

https://github.com/FreeRTOS/FreeRTOS-Kernel/compare/d6bccb1f4...Skptak:FreeRTOS-Kernel:fixMikroCFormatting

* portable/MikroC/ARM_CM4F/port.c : 
more trace macro are added in future commits
* portable/MikroC/ARM_CM4F/portmacro.h :
more trace macro are added in future commits

**Review by aggarg — APPROVED** [review]

**Pull request merged**
