### PR TITLE
Fix RISC-V configMTIMECMP_BASE_ADDRESS (64-bit) stored in 32-bit int

### PR DESCRIPTION
**Pull request by vishwamartur**
Related to #189

Update `configMTIMECMP_BASE_ADDRESS` to be stored in a 64-bit integer.

* Change the type of `ullMachineTimerCompareRegisterBase` to `uint64_t` in `portable/GCC/RISC-V/port.c`.
* Change the type of `ullMachineTimerCompareRegisterBase` to `uint64_t` in `portable/IAR/RISC-V/port.c`.
* Update the initialization of `ullMachineTimerCompareRegisterBase` to use `configMTIMECMP_BASE_ADDRESS` in both files.

### CODE REVIEW

**Comment by ActoryOu** [comment]
Hello @vishwamartur,
Thanks for your contribution! Could you share your verification results on this PR? I'm curious what platform you're using to verify this.

Thank you!

**Comment by aggarg** [comment]
@vishwamartur Would you please share how you tested these changes on 32-bit and 64-bit platforms as the same code is used on both the platforms.

**Comment by vishwamartur** [comment]
Hi @ActoryOu and @aggarg,

Thank you for the feedback! I haven’t tested these changes yet, as I currently lack access to a compatible platform for both 32-bit and 64-bit verification. If you have any suggestions for alternative testing methods or an emulator that could support this setup, I’d be glad to give it a try.

Thanks again!

**Review by aggarg — APPROVED** [review]

**Comment by aggarg** [comment]
I tested this change [using Qemu](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/RISC-V-Qemu-virt_GCC) and looks good to me. 


On a side note, I'd suggest to use the PR template as it guides you what all information to provide when creating a PR (which includes testing).

**Review by kar-rahul-aws — APPROVED** [review]

**Comment by landretk** [comment]
This produces a compiler warning on 32-bit because it truncates a 64-bit integer into a pointer. 

FreeRTOS doesn't appear to have a type that can hold an integer with the same width as a pointer. `uintptr_t` seems to be disallowed because it's C99, `unsigned long` because it's not a stdint or freertos type although it's correct for ilp32 and lp64, and none of the freertos types are defined as being able to hold an address. `configMTIMECMP_BASE_ADDRESS` might need to be used directly without being stored in an intermediate variable, unless `UBaseType_t` would be accepted

**Comment by aggarg** [comment]
> unless UBaseType_t would be accepted

Thank you pointing this out. I agree that we should use UBaseType_t as it is defined correctly based on XLEN. Here is the PR to address this - https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1258. 

Thank you again for bringing this to our attention.

**Pull request merged**
