### PR TITLE
Declare vApplicationMallocFailedHook function in task.h instead in each C heap file

### PR DESCRIPTION
**Pull request by pierrenoel-bouteville-act**
Declare vApplicationMallocFailedHook function in task.h instead in each C heap file

Description
-----------
vApplicationMallocFailedHook  was declared in each Heap file. which forces users to declare it and can cause problems if the prototype of the function changes.
So I done like other hook, example vApplicationStackOverflowHook.

Test Steps
-----------
Compile with GCC on my project

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by n9wxu — DISMISSED** [review]

**Comment by pierrenoel-bouteville-act** [comment]
I now but it is with all failed hook and there is no heap.h.
2 options:
* put a heap.h just for it
* put it in all portmacro.h files

**Comment by aggarg** [comment]
Please move the declaration to this file after all the heap function declarations - https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/include/portable.h#L189

**Comment by aggarg** [comment]
Do you want to do it or do you want us to do it?

**Comment by aggarg** [comment]
Thank you!

**Review by aggarg — APPROVED** [review]

**Review by archigup — APPROVED** [review]

**Pull request merged**
