### PR TITLE
Synopsys ARC v1 Port: add support to Synopsys ARC v1 series cores

### PR DESCRIPTION
**Pull request by YuguoWH**
Description
-----------
ARC v1 cores include ARC605, ARC610d, and ARC710d
These code can be built with GNU toolchain or Metaware_mcc toolchain
Also modify ARC port license headers

-------------------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by YuguoWH** [comment]
Hi, I have a question about the license in file header of these Synopsys port files: Currently they all says copyright Amazon, it is possible to change that to Synopsys? Or we could attach another Synopsys copyright announcer after the existing Amazon one? (as suggested in [CONTRIBUTING.md](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/master/CONTRIBUTING.md#licensing))
Thanks.

**Comment by RichardBarry** [comment]
It if fine to only have a Synopsys copyright if the port layer was created by Synopsys (which I think it was), rather than modified from a different port.

**Comment by n9wxu** [comment]
We are currently working towards a release and would love to have ARC support included.  If you can update the copyrights to your satisfaction I will approve this PR.

**Comment by YuguoWH** [comment]
Hi @RichardBarry @n9wxu, thanks for your reply and suggestions, I update the copyrights headers and rebase the PR to the latest master branch.

**Comment by YuguoWH** [comment]
Had this PR rebased to eliminate conflicts

**Comment by YuguoWH** [comment]
Hi, do you have any reviews or advices on this PR? Thanks.

**Comment by RichardBarry** [comment]
I note you have also changed the license - this Github repo is marked as being MIT licensed and the one you changed it to is very similar.  Preference is to only change the copyright, not the license.

**Comment by YuguoWH** [comment]
@RichardBarry  Thank you for your review, I drop last commit and submit a new one, now only copyright is changed.

**Review by n9wxu — APPROVED** [review]

**Pull request merged**
