### PR TITLE
Feature/mchp updates

### PR DESCRIPTION
**Pull request by alexmchp**
Updated portables for Microchip AVR Dx and Mega0

Description
-----------
-	Update AVR GCC port files (now the port.c and portmacro.h files are identical for AVR_Mega0 and AVR_Dx families) 
-	Add support for low-power tickless mode in portable files for AVR_Dx and AVR_Mega0

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aggarg** [comment]
Hi @alexmchp, 

Thank you for your contribution. This FreeRTOS port falls into the category of "Partner Supported FreeRTOS Ports" as per the criteria recently published [here](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/portable/ThirdParty/README.md). Accordingly, would you please move this port to the [Partner Supported FreeRTOS Ports Repo](https://github.com/FreeRTOS/FreeRTOS-Kernel-Partner-Supported-Ports/tree/main). Similarly the FreeRTOS demo in [this PR](https://github.com/FreeRTOS/FreeRTOS/pull/672) should be moved to [Partner Supported FreeRTOS Demos Repo](https://github.com/FreeRTOS/FreeRTOS-Partner-Supported-Demos/tree/main).

Let me know if you would like me to move these and I will be happy to do that.

Thanks.

**Comment by alexmchp** [comment]
Hi @aggarg, Thanks for the update. I will make sure future changes are done in the correct locations. It would be awesome if this time you could move them to the appropriate repos?

**Comment by alexmchp** [comment]
Hi @aggarg , any update on this ?

**Comment by aggarg** [comment]
Hi @alexmchp, Sorry it slipped my mind. Will look into it and update you.

**Comment by aggarg** [comment]
Hi @alexmchp, I moved the ports and opened this PR - https://github.com/FreeRTOS/FreeRTOS-Kernel-Partner-Supported-Ports/pull/3

Please review and let me know if everything looks good.

**Comment by aggarg** [comment]
I am closing this PR as  I have merged the above. Please let me know if anything looks off.

**Comment by alexmchp** [comment]
@aggarg thanks! awesome work!
what about [this PR](https://github.com/FreeRTOS/FreeRTOS/pull/672), can you move that too, or should we do it?

**Comment by aggarg** [comment]
@alexmchp  - With [this PR](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/394), I  have removed these ports from the original location and added a README telling their new location. 

Would you please move the demo projects to https://github.com/FreeRTOS/FreeRTOS-Partner-Supported-Demos? You will need to update source path and include paths for the port files.

Thanks.

**Comment by mchpcristianpop** [comment]
@aggarg - I've created a [new PR](https://github.com/FreeRTOS/FreeRTOS-Partner-Supported-Demos/pull/2) to https://github.com/FreeRTOS/FreeRTOS-Partner-Supported-Demos. The projects are now updated to new structure. Please let me know if anything else is needed

**Comment by aggarg** [comment]
@mchpcristianpop Thank you for your contribution.

**Pull request closed without merging**
