### PR TITLE
Add CC-RH port for Renesas F1Kx devices

### PR DESCRIPTION
**Pull request by TrongNguyenR**
Add CC-RH port for Renesas F1Kx devices

Description
-----------
Add port files (port.c, portasm.s, portmacro.h) for CC-RH core for Renesas F1Kx devices.

Test Steps
-----------
The test project can be found [here](https://github.com/FreeRTOS/FreeRTOS-Community-Supported-Demos) (`RH850_F1Kx_CCRH`). This project contains example tasks and configurations to help you get started with FreeRTOS on the RH850/F1K and F1Kx.

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------
None

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by archigup — APPROVED** [review]

**Comment by chinglee-iot** [comment]
@TrongNguyenR 
Thank you for creating this PR. We are still reviewing this PR and trying to run the demo with this port if the hardware is available to us. We thank you for your patience.

**Comment by TrongNguyenR** [comment]
Hello @chinglee-iot,

> @TrongNguyenR Thank you for creating this PR. We are still reviewing this PR and trying to run the demo with this port if the hardware is available to us. We thank you for your patience.

Thanks for your notice. We are working on preparing device for your testing, please wait.
Meanwhile, I understand that source code review is on-going, is it correct?
Thanks for your support.

**Comment by TrongNguyenR** [comment]
Hello @chinglee-iot,
We are preparing to send board from Renesas India by Jul 31. Please take it for your information.

**Comment by TrongNguyenR** [comment]
Hello @chinglee-iot -san,
I got information that the board has already arrived at your side (Receiver: Mr. Nikhil Kamath).
Please let me know if you got any issue.

**Comment by aggarg** [comment]
Thank you @TrongNguyenR! We received the board. We will get back to you.

**Comment by aggarg** [comment]
@TrongNguyenR Would you please rebase your branch so that it is up-to-date with main?

**Comment by TrongNguyenR** [comment]
@aggarg, we have synced our branch, it's up to date now.

**Review by aggarg — APPROVED** [review]

**Review by kar-rahul-aws — APPROVED** [review]

**Comment by aggarg** [comment]
Thank you for your contribution!

**Pull request merged**
