### PR TITLE
TF-M integration with FreeRTOS Kernel

### PR DESCRIPTION
**Pull request by Sherryzhang2**
Title
TF-M integration with FreeRTOS Kernel

Description
-----------
Trusted Firmware M(TF-M) is an open-source project. It provides a reference implementation of PSA for Arm M-profile architecture.

This port adds the support that FreeRTOS applications can call the secure services in Trusted Firmware M(TF-M) through Platform Security Architecture(PSA) API based on the ARM Cortex-M33 platform.

Test Steps
-----------
This port has been tested on ARM Cortex-CM33 based platform.

Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS/issues/184

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by RichardBarry** [comment]
Is this the same code linked to from this blog? https://freertos.org/2020/07/security-for-arm-cortex-m-devices-with-freertos.html

**Comment by davwan01** [comment]
> Is this the same code linked to from this blog? https://freertos.org/2020/07/security-for-arm-cortex-m-devices-with-freertos.html

Hi Richard,
It's the same thing (adding TF-M support) but not exactly the same code. This patch is based on the latest TF-M release v1.1 and latest FreeRTOS-Kernel v10.3.1. Basically, we rebased to latest TF-M and FreeRTOS-Kernel for this PR.
The main feature changed between this PR and the blog's code is that we disabled the secure context management API because it's not required until TF-M supports multiple secure contexts (which is ongoing).

**Comment by RichardBarry** [comment]
Thanks.  One of our team is going to take a look.  If all is ok we will ask for the contribution to be moved to the third-party directory (https://github.com/FreeRTOS/FreeRTOS-Kernel/tree/master/portable/ThirdParty).

Do you have a project that demonstrates its use?  Maybe in the Keil or other simulator to make the code as accessible as possible?

**Comment by davwan01** [comment]
Yes. There's a demo Keil project in Linaro repository - https://github.com/Linaro/amazon-freertos/pull/1
It's based on the "old" integration mentioned in the blog (https://freertos.org/2020/07/security-for-arm-cortex-m-devices-with-freertos.html)  but it's basically the same as this one which is rebased to latest TF-M/FreeRTOS-Kernel.

**Comment by davwan01** [comment]
Hi @RichardBarry , do you need any further information on the PR review? Please feel free to let me know. Thanks!

**Comment by RichardBarry** [comment]
No further info required at the moment thanks.  One of our engineers is scheduled to do a deeper dive, so there may be further questions then.  Apologies for the delay but we are preparing some release code so currently working our way through a list of small items prior to getting around to this.

**Comment by davwan01** [comment]
OK, Thanks. If any further info needed, just ping me. 😊

**Comment by aggarg** [comment]
Apologies for the delay. I just finished reviewing this code. It seems that the changes are for removing secure side context management support.

If that is the case, would Non-TrustZone ports serve your purpose: https://github.com/FreeRTOS/FreeRTOS-Kernel/tree/master/portable/GCC/ARM_CM33_NTZ/non_secure

Non-TrustZone ports do not have any secure side context management support and that seems to be the purpose of your changes.

Thanks.

**Comment by davwan01** [comment]
Hi @aggarg , thanks for the review!
There are two major differences with NTZ port:

- This port adds the OS lock wrapper (required by TF-M) to avoid reentry TF-M running in the secure side (that's why we can remove the secure context management at the moment)
- We are implementing multiple secure context support in TF-M. When it's finished, we will add new secure context management (different with current FreeRTOS implementation) in this port.

So, we suggest adding this new PSA/TF-M port for flexibility. And it's actually using TZ, so NTZ may confuse people. 😊
Thanks.

**Comment by aggarg** [comment]
Hi @davwan01 , Thanks for your response!

I think when you have multiple secure context support, this port will become different - currently it is doing exactly what NTZ port does. Also, I think mutex wrapper should be kept outside of FreeRTOS.

Our ARMv8-M ports comprise of a master copy and multiple replicas as mentioned here: https://www.freertos.org/2020/04/using-freertos-on-armv8-m-microcontrollers.html#CONTRIBUTION

To ensure that you update this TFM port at your convenience, please move your port to `portable\ThirdParty\GCC\` directory.  Please also note that you will need to keep your copies of `port.c`, `portmacro.h`, `portasm.c` and other files up-to-date as we update our versions. 

Thanks.

**Comment by davwan01** [comment]
Hi @aggarg ,

OK, I think I got your point. As there is an overhead to keep the files (`port.c`,  `portasm.c`, ... ) in sync-up with your update. So, we can just add the instructions in the README to point the files in CM33-NTZ now. When we add our own secure context management functions, then add the files back in our folder and maintain them in the future. Am I correct?

For the wrapper, it is the interface between a specific RTOS and TF-M NS side dispatcher (source files are in TF-M folder, didn't put the local fork here). Basically, for the RTOS synchronization primitives. NS dispatcher and the wrapper will be built together with the FreeRTOS running in the non-secure side. So, that's where this proposal came from.

For the third-party folder, does portable\ThirdParty\GCC\arm\CM33_TFM work for you? Basically, suggesting put CMxx to the arm folder.

Summary - I suggest:

- Move everyting to the folder portable\ThirdParty\GCC\arm\CM33_TFM
- Remove the files which are similar to CM33-NTZ and point to portable/GCC/ARM_CM33_NTZ for the source files
- CM33_TFM only has the os wrapper (for NS side dispatcher) file.

Doe this sound good to you?
Thanks.

**Comment by aggarg** [comment]
> When we add our own secure context management functions, then add the files back in our folder and maintain them in the future. Am I correct?

Yes. And at that point, I can look into your changes and see if we can update our ports in some way to ensure that you do not need to maintain a separate copy of common files.

> For the wrapper, it is the interface between a specific RTOS and TF-M NS side dispatcher (source files are in TF-M folder, didn't put the local fork here). Basically, for the RTOS synchronization primitives. NS dispatcher and the wrapper will be built together with the FreeRTOS running in the non-secure side. So, that's where this proposal came from.

I understand that part. The reason I said to keep it out of FreeRTOS is because it seems more intuitive to keep wrapper out of what is wrapped. But as you suggested, we can keep it in the port directory. 

> For the third-party folder, does portable\ThirdParty\GCC\arm\CM33_TFM work for you?

I'd suggest `portable\ThirdParty\GCC\ARM_CM33_TFM` to be consistent with our other ARM ports. 

>* Move everyting to the folder portable\ThirdParty\GCC\arm\CM33_TFM
>* Remove the files which are similar to CM33-NTZ and point to portable/GCC/ARM_CM33_NTZ for the source files
>* CM33_TFM only has the os wrapper (for NS side dispatcher) file.

Sounds perfect (with the change of folder name `portable\ThirdParty\GCC\ARM_CM33_TFM`). 

Thanks.

**Comment by Sherryzhang2** [comment]
Hi @aggarg ,

OK, we will name the folder as portable\ThirdParty\GCC\ARM_CM33_TFM folder as you suggested.

Besides the os_wrapper_freertos.c, I think the file port.c should also be put into the portable\ThirdParty\GCC\ARM_CM33_TFM folder. The reason is that when starting the scheduler, the TF-M interface tfm_ns_interface_init() should be called in the port.c. In tfm_ns_interface_init(), the os_wrapper_mutex_create() in the os_wrapper_freertos.c is called to create the mutex.

Does that make sense?

**Comment by aggarg** [comment]
`tfm_ns_interface_init` function, as the name suggests, is probably intended to initialize the NS side of TFM. Is is better to call it from the application - like the application calls it before calling `vTaskStartScheduler`? 

The reason I am suggesting to avoid making a copy of `port.c` is because you will need to keep it up-to-date. For example, I made some changes in this PR https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/85 which are missing from your copy of port.c file. It is because of this same reason I suggested in one of my previous comments that once your secure context changes are in, I will look into what can be done to ensure that you do not need to make a copy. 

What do you think?

Thanks.

**Comment by Sherryzhang2** [comment]
Make sense. 
We will try the solution you proposed and update the PR.

**Comment by davwan01** [comment]
Hi @Sherryzhang2 , 
Just a reminder that please make sure the proper error is returned if the application didn't/forgot to call the tfm_ns_interface_init function.
Thanks.

**Comment by Sherryzhang2** [comment]
@davwan01 Thanks for your reminding. That a good point.
If the tfm_ns_interface_init is not called in the application, TFM_ERROR_GENERIC error will be returned when calling a TF-M service in the Nonsecure side.

**Comment by Sherryzhang2** [comment]
@aggarg I have updated the PR according to the solution we discussed above. Could please review it?

Thanks!

Sherry

**Comment by aggarg** [comment]
Thank you for the changes @Sherryzhang2 and writing detailed instructions. Looks good to me.

Just for my understanding - I see that your instructions ask to copy all the files in ```freertos_kernel\portable\GCC\ARM_CM33_NTZ``` into the ```freertos_kernel\portable\GCC\ARM_CM33_TFM``` folder. Is it because your build system uses the `ARM_CM33_TFM` folder?

Thanks.

**Review by aggarg — APPROVED** [review]

**Review by cobusve — APPROVED** [review]

**Comment by Sherryzhang2** [comment]
> Thank you for the changes @Sherryzhang2 and writing detailed instructions. Looks good to me.
> 
> Just for my understanding - I see that your instructions ask to copy all the files in `freertos_kernel\portable\GCC\ARM_CM33_NTZ` into the `freertos_kernel\portable\GCC\ARM_CM33_TFM` folder. Is it because your build system uses the `ARM_CM33_TFM` folder?
> 
> Thanks.

My build system uses the `ARM_CM33_TFM` folder. But the reason I add this instruction is to make it clear which files are exactly required to integrate with TF-M.

Regards,
Sherry

**Comment by davwan01** [comment]
Thanks @aggarg . May I know if this patch will be picked up by Freertos Kernel present in Amazon FreeRTOS? The users of pkcs11-psa shim layer could get benefit from this integration.

**Comment by aggarg** [comment]
Yes, it should be picked in the next release - FreeRTOS kernel in the Amazon FreeRTOS is a sub-module of this repo.  

Thanks.

**Comment by davwan01** [comment]
That's great! Thanks!

**Pull request merged**
