### PR TITLE
Run kernel demos and unit tests for PR changes

### PR DESCRIPTION
**Pull request by aggarg**
Description
-----------
Kernel demos check builds multiple demos from FreeRTOS/FreeRTOS repo and unit tests check runs unit tests in `FreeRTOS/FreeRTOS`. Both of these checks used main branch of `FreeRTOS-Kernel`. This PR updates these checks to use the changes in the Pull Request to ensure that the changes in the Pull Request are verified.

Test Steps
-----------
Tested using a test PR to my fork - https://github.com/aggarg/FreeRTOS-Kernel/pull/1

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by sirnish — APPROVED** [review]
GTG

**Comment by urutva** [comment]
Same changes are needed in `.github/workflows/ci.yml`, and `.github/workflows/git-secrets.yml`.

**Comment by aggarg** [comment]
> Same changes are needed in `.github/workflows/ci.yml`, and `.github/workflows/git-secrets.yml`.

In those checks we are already using `actions/checkout` which checks out the PR changes by default.This is from the [ReadMe ](https://github.com/actions/checkout/blob/releases/v2/README.md) of the `actions/checkout`:
```
# The branch, tag or SHA to checkout. When checking out the repository that
# triggered a workflow, this defaults to the reference or SHA for that event.
# Otherwise, uses the default branch.
```

To be doubly sure, I created this test PR in my fork which introduced formatting and spell failure and you can see that corresponding checks failed - https://github.com/aggarg/FreeRTOS-Kernel/pull/2

**Comment by urutva** [comment]
> > Same changes are needed in `.github/workflows/ci.yml`, and `.github/workflows/git-secrets.yml`.
> 
> In those checks we are already using `actions/checkout` which checks out the PR changes by default.This is from the [ReadMe ](https://github.com/actions/checkout/blob/releases/v2/README.md) of the `actions/checkout`:
> 
> ```
> # The branch, tag or SHA to checkout. When checking out the repository that
> # triggered a workflow, this defaults to the reference or SHA for that event.
> # Otherwise, uses the default branch.
> ```
> 
> To be doubly sure, I created this test PR in my fork which introduced formatting and spell failure and you can see that corresponding checks failed - [aggarg#2](https://github.com/aggarg/FreeRTOS-Kernel/pull/2)

Ah that makes sense. `actions/checkout` creates a merge request after pulling in the PR changes. When I checked https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/645/checks#step:2:487 I was expecting the PR commit hash and hence thought that PR changes weren't fetched.

**Comment by aggarg** [comment]
> Nitpick: Can we please remove the PR SHA from https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/.github/workflows/kernel-checks.yml#L31?

Done.

**Review by urutva — APPROVED** [review]

**Review by paulbartell — APPROVED** [review]

**Comment by paulbartell** [comment]
Good catch. One thought.. Perhaps we should use paired branch names for Kernel Pull Requests that need to update both the Unit Tests and Kernel Source concurrently.

For example.. If I need to make a change to the kernel and unit tests, I would create a branch with the same name in FreeRTOS/FreeRTOS-Kernel and FreeRTOS/FreeRTOS. 

Then when running CI checks in either repository, the CI script would checkout the same branch name in the opposite repository if that branch exists, otherwise it would default to the main branch in the opposite repository.

**Review by amazonKamath — APPROVED** [review]

**Pull request merged**
