### PR TITLE
Enable Interrupts don't need NOP before portENABLE_INTERRUPTS

### PR DESCRIPTION
**Pull request by mayl**
Description
-----------

Test Steps
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aggarg** [comment]
Source code:
```
void fun( void )
{
  volatile int i = 0;

  portDISABLE_INTERRUPTS();
  i++;
  i++;
  portENABLE_INTERRUPTS();
}

```

Generated assembly when using IAR intrinsics - 
```
fun:
    SUBA    #0x2, SP
    MOV.W   #0x0, 0(SP)

   /* portDISABLE_INTERRUPTS(); */
   DINT
   NOP
   NOP
   
   /* i++; */
   ADD.W   #0x1, 0(SP)
   
   /* i++; */
   ADD.W   #0x1, 0(SP)
   NOP <-- Notice this NOP before EINT.
   
   /* portENABLE_INTERRUPTS(); */
   EINT
   NOP

   ADDA    #0x2, SP
   RETA

```

Source code - 
```
void fun( void )
{
  volatile int i = 0;

  i++;
  i++;
  portENABLE_INTERRUPTS();
}
```

Generated assembly when using IAR intrinsics - 
```
fun:
    SUBA    #0x2, SP
    MOV.W   #0x0, 0(SP)

    /* i++; */
    ADD.W   #0x1, 0(SP)

    /* i++; */
    ADD.W   #0x1, 0(SP)
    NOP <-- Notice this NOP before EINT.

    /* portENABLE_INTERRUPTS(); */
    EINT
    NOP

    ADDA    #0x2, SP
    RETA
```

Source code:
```
void fun( void )
{
  portENABLE_INTERRUPTS();
}
```


Generated assembly when using IAR intrinsics - 
```
fun:
    /* portENABLE_INTERRUPTS(); */
    NOP <-- Notice this NOP before EINT.
    EINT
    NOP

    RETA
```

In all the three examples, IAR intrinsic inserts a NOP before EINT. CCS also complains if you do not have a NOP before EINT. Why do you think we do not need this NOP?

**Comment by mayl** [comment]
`portDisableInterrupts()` is not an IAR intrinsic...  It's defined by FreeRTOS as an `asm` directive.  Unless there is more to these examples than you shared, these only prove that IAR will emit the instructions you tell it to...  To get the intrinsics behavior you need to use the intrinsic `__enable_interrupt()` `__disable_interrupt` functions.

I've read the MSP430 programming manual on DINT and EINT (see below).  What in the below suggests executing the instruction before EINT is an issue?  

image

image

It is unclear to me what the even potential concurrency hazard is by having an instruction executed before an EINT... Obviously it's _before_ the EINT so it's _intended_ to be executed.  This also seems to be reflected in the "rules for enabling and disabling interrupts" where the only reference to NOP before EINT is in the case of NOP between DINT and EINT.  I'm not sure how that's not the same as "NOP after DINT" which FreeRTOS already has.  

image

**Comment by aggarg** [comment]
> portDisableInterrupts() is not an IAR intrinsic... It's defined by FreeRTOS as an asm directive. Unless there is more to these examples than you shared, these only prove that IAR will emit the instructions you tell it to... 

Sorry for not being clear. When I executed the example above, I checked out the commit before the recent change i.e. `portENABLE_INTERRUPTS` is defined as -

```
#define portENABLE_INTERRUPTS()     _EINT(); _NOP()
```

And `_EINT ` is defined as -
```
#define _EINT()        __enable_interrupt()
```

That is why I said that the above code was using IAR intrinsic.

**Comment by aggarg** [comment]
> It is unclear to me what the even potential concurrency hazard is by having an instruction executed before an EINT... 

I am not sure about that but I guess we wanted to keep emitting the same assembly after removing intrinsic.

**Comment by mayl** [comment]
> > portDisableInterrupts() is not an IAR intrinsic... It's defined by FreeRTOS as an asm directive. Unless there is more to these examples than you shared, these only prove that IAR will emit the instructions you tell it to...
> 
> Sorry for not being clear. When I executed the example above, I checked out the commit before the recent change i.e. `portENABLE_INTERRUPTS` is defined as -
> 
> ```
> #define portENABLE_INTERRUPTS()     _EINT(); _NOP()
> ```
> 
> And `_EINT ` is defined as -
> 
> ```
> #define _EINT()        __enable_interrupt()
> ```
> 
> That is why I said that the above code was using IAR intrinsic.

_EINT() and _NOP() are legacy compatibility layers from very old versions of IAR (1.x).  The last 1.x version was [released 22 years ago in 2002](https://updates.iar.com/?key=255b9d94ee29404bb4178db6863cb879&version=1.26B)

 
I suspect based on my previous experiments if you use the raw `__enable_interrupt()` `__disable_interrupt()` you'll get the correct behavior (see comment from IAR engineer [here](https://www.embeddedrelated.com/showthread/msp430/34977-1.php#tabs1-chronological)).  I don't have access to IAR at home, but I can try again and see if I get the same behavior as you.

**Comment by aggarg** [comment]
Source code -
```
void fun( void )
{
  __enable_interrupt();
}
```

Generated assembly:
```
fun:
    /* __enable_interrupt(); */
    NOP <-- Notice this NOP.
    EINT

    RETA
```

**Comment by aggarg** [comment]
@mayl Do you need anything else or should I close this PR?

**Comment by mayl** [comment]
I'm still trying to get to the bottom of it.

[this reply](https://e2e.ti.com/support/microcontrollers/msp-low-power-microcontrollers-group/msp430/f/msp-low-power-microcontroller-forum/1403121/msp430fr5969-nop-before-eint) indicates a nop is needed before, but not after.

[this reply](https://e2e.ti.com/support/microcontrollers/msp-low-power-microcontrollers-group/msp430/f/msp-low-power-microcontroller-forum/382388/compiler-warning-w0005-nop-required-before-set-of-gie-bit) indicates that a nop before is overkill and only necessary when the previous instruction manipulated the GIE bit.

**Comment by aggarg** [comment]
Thank you for your response. I will keep it open then.

**Comment by aggarg** [comment]
One of my colleague pointed to the section 8.2 in this doc which seems relevant - https://www.ti.com/lit/ug/slau646f/slau646f.pdf?ts=1724857570924&ref_url=https%253A%252F%252Fwww.google.com%252F.

**Comment by aggarg** [comment]
@mayl Have you made any progress? Do you want me to keep the PR open still?

**Comment by aggarg** [comment]
I am closing this PR. Feel free to reopen if you need anything from us.

**Pull request closed without merging**
