### PR TITLE
Port Arm Cortex-M55

### PR DESCRIPTION
**Pull request by gbrtth**
Description
-----------
Add Cortex-M55 support based on Cortex-M33 support.
M55 files extended only with MVE context save-restore mechanism. The same mechanism is used as in case of FPU on M33.
No assembly changed compared to M33, only `configENABLE_MVE` macro is added.
ARM_CM55_TFM port is also added.

Test Steps
-----------
TZ and MPU demos run from FreeRTOS/FreeRTOS repository.

Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/477

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mark-horvath-arm** [comment]
> Thanks for this.
> 
> As pre-processing the new configENABLE_MVE compile time constant is the only code generating difference between the Cortex-M33 and Cortex-M55 ports I would like to combine the two into a single port. Our team can manage that, and then do likewise for the IAR port.
> 
> We also need to clean up the port naming, or at least provide mapping for users so they know which port to use. For example, currently you use the Cortex-M3 port for both Cortex-M3 and Cortex-M4 devices that don't have an MPU, and use the Cortex-M4F port for both Cortex-M4 with MPU and Cortex-M7 devices. Once the PR is combined into a single port with the Cortex-M33 that will be applicable to both Cortex-M33 and Cortex-M55 parts.....documentation issue rather than a tech issue.

Hi @RichardBarry!

Did you decide how to merge the M33 and M55 kernel ports? Can we help with this task?

**Comment by RichardBarry** [comment]
Apologies this has taken a while - we have a lot of folks working on some launches for the upcoming embedded world - I will ask this is bumped to the top.

**Comment by aggarg** [comment]
I see that we are adding `configENABLE_MVE` and it does exactly what `configENABLE_FPU` does. What is need of having a separate macro? 

The following text from [here ](https://developer.arm.com/documentation/101273/r0p2/The-Cortex-M55-Processor--Reference-Material/Armv8-1-M-MVE-overview)indicates that MVE requires FPU and therefore, just enabling FPU should be enough?:

```
In Cortex-M55, integer and half-precision and single-precision floating-point can only be included if the floating-point functionality is included. If floating-point functionality is not included, then only the integer subset of MVE can be optionally implemented.
```

Thanks.

**Comment by aggarg** [comment]
Thank you for your reply. Just for the clarification - 

```
If floating-point functionality is not included, then the MVE options can be either of the following:
* MVE not included.
* Integer subset of MVE included.
```

In the scenario when floating-point functionality is not included and Integer subset of MVE is included, are the registers S0-S31 present?

**Comment by gbrtth** [comment]
Yes, MVE uses 8 vector registers (Q0-Q7), and according to the architecture reference manual these alias onto the FPU register file.

For example, the VADDV instruction, which adds the elements of a vector register and saves it into a general-purpose register, can be used with integer MVE without FPU.
Also a VMOV version (between general-purpose and single-precision register) can also be used by MVE without FPU.

**Comment by mark-horvath-arm** [comment]
Hi All! Would you need more information on this topic? Is there anything we can do to help the progress?

**Comment by RichardBarry** [comment]
I think the work to integrate the Cortex-M55 changes into the Cortex-M33 port has been done - although I'm not sure if a PR was created yet.

**Comment by alfred2g** [comment]
Hi, @RichardBarry , @mark-horvath-arm 
https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/494
here's the PR for consolidating M33 and M55

**Comment by aggarg** [comment]
Cortex-M55 support has been merged with this PR - https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/494

The major change we did is to not create M55 copy in the common location and instead use the M33 one. 

I am closing this PR. Let me know if you need anything else from us.

Thanks.

**Pull request closed without merging**
