### PR TITLE
Fix pxTopOfStack calculation in configINIT_TLS_BLOCK for picolib

### PR DESCRIPTION
**Pull request by bebebib-rs**
Description
-----------
The  `pxTopOfStack` calculation in `configINIT_TLS_BLOCK` for picolib needs to decrement  `pxTopOfStack`  in order to meet the expectation of `pxPortInitialiseStack` function. 
 
Details described in https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/714.

Test Steps
-----------
Described in attached issue. 

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------
* https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/714

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aggarg** [comment]
As I explained in this comment, changing all the ports is a massive change. I'd rather implement a workaround that I described [in this comment](https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/714#issuecomment-1651199662).

**Comment by jefftenney** [comment]
I think the [code suggested](https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/714#issuecomment-1651199662) by @aggarg is not only the most readable but also the most correct.

Function `pxPortInitialiseStack()` expects/requires a _pre-decremented_ value for `pxTopOfStack`. Function `prvInitialiseNewTask()` initializes `pxTopOfStack` to a pre-decremented value.

[Here](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/tasks.c#L1518-L1519) is the initialization code for `pxTopOfStack`:

```
    pxTopOfStack = &( pxNewTCB->pxStack[ ulStackDepth - ( uint32_t ) 1 ] );
    pxTopOfStack = ( StackType_t * ) ( ( ( portPOINTER_SIZE_TYPE ) pxTopOfStack ) & ( ~( ( portPOINTER_SIZE_TYPE ) portBYTE_ALIGNMENT_MASK ) ) );
```

_This code pre-decrements (and then aligns) pxTopOfStack.  Note the "- ( uint32_t ) 1"._

In between this initialization code and the call to `pxPortInitialiseStack()` is a call to `configINIT_TLS_BLOCK`.  If `configINIT_TLS_BLOCK` does not modify `pxTopOfStack`, then the value passed to `pxPortInitialiseStack()` is the default, pre-decremented value.  However, if `configINIT_TLS_BLOCK` modifies pxTopOfStack, it must be required to pre-decrement the final value. If it does _not_ pre-decrement the final value, then the contract with `pxPortInitialiseStack()` is broken.  Unfortunately, the implementation of `configINIT_TLS_BLOCK` for picolibc in v10.6.0 does not pre-decrement the final value, which is not the correct behavior.  Gaurav's suggestion seems to fix the issue cleanly and directly.

**Comment by bebebib-rs** [comment]
Ah, I missed that initialization code for the top of the stack, agreed, the suggested code is the best change.

**Review by aggarg — APPROVED** [review]

**Review by kar-rahul-aws — APPROVED** [review]

**Comment by aggarg** [comment]
Thank you for clarification @jefftenney and thank you for the PR @bebebib-rs.

**Pull request merged**
