### PR TITLE
Port/xmos/upstream support

### PR DESCRIPTION
**Pull request by dachalco**
upstream port support based off xmos' fork. This accounts for kernel portion. There's a FreeRTOS/FreeRTOS xmos fork with Demo changes which will need to submodule kernel with these changes.

Description
-----------

Test Steps
-----------

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yuhui-zheng** [comment]
- In general, if a port is to be reviewed, please provide detailed information for what this port does and how to use this port. (A very good example PR #48 ) And even better, a working project and detailed in formation of what has been tested. 

- Why we need to touch kernel source files to bring in this port? (case in point ```event_groups.c```, ```FreeRTOS.h```, ```timers.c```)

- Please make sure path follows <compiler>/<architecture>. (Is the compiler XMOS?) And please confirm the license entity "XMOS Ltd" is intended.

**Comment by dachalco** [comment]
Board used for development/testing: [XK-USB-MIC-UF216](https://www.digikey.com/product-detail/en/xmos/XK-USB-MIC-UF216/880-1120-ND/6005986)

- A project exists in [this FreeRTOS git fork](https://github.com/xmos/FreeRTOS/tree/feature/upstream-support/FreeRTOS/Demo/XCORE200_XCC). It depends on these kernel changes to work appropriately. The linked demo contains minimal test demos, partest, intqueue test, and more. They're listed [here](https://github.com/xmos/FreeRTOS/blob/feature/upstream-support/FreeRTOS/Demo/XCORE200_XCC/RTOSDemo/src/test.c#L83).

- The kernel source changes add a _new_ macro that defaults as whitespace: `portTIMER_CALLBACK_ATTRIBUTE`. It is used to add XMOS XCC specific `__attributes
__` to functions and function pointers, specifically those that can be timer callback functions. With this association, their compiler's static analyzer knows which function to explore when encountering the tagged function pointers.

- The compiler is XMOS' `XCC` which was originally part of the path. However there is name collision as `portable/ThirdParty/XCC` already exists and is used by xtensa for _their_ `xcc` compiler (same name, different compilers). Hence the XMOS path component. I suppose `ThirdParty/XCC/XMOS` could work, but it could confuse some into thinking `XCC/XMOS` and `XCC/Xtensa` use the same compiler when they don't. Thoughts? Regarding licensing, I based the policy on other `portable/ThirdParty` ports such as xtensa's [`ThirdParty/XCC`](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/master/portable/ThirdParty/XCC/Xtensa/port.c#L31) and [`ThirdParty/CDK`](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/master/portable/ThirdParty/CDK/T-HEAD_CK802/port.c#L2). With xmos permission, I appended our MIT licenses accordingly (See [e43b040](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/55/commits/e43b0408b1b83a0d266e8db24baaa08377faf30d)).

It's under `ThirdParty` as xmos provided the code. PR submitted by me as I needed to make a few changes. The upcoming `FreeRTOS/FreeRTOS` demo that will follow this PR should answer most of the "How To Use It" questions. For verification purposes, you can clone the demo linked above, replace its FreeRTOS/Source with [my fork containing these changes](https://github.com/dachalco/FreeRTOS-Kernel/tree/port/xmos/upstream-support). Test success is indicated by LEDS D2 and D3 continuously toggling every 3 seconds.

**Comment by dachalco** [comment]
They have there own `xcc` compiler, different and not to be confused with xtensa's `xcc` compiler.

Added new commits for moving macro to same line as decorated code, adding comment to describe the macro in code, and relocating port path to include compiler name while avoiding name collision with Xtensa's XCC. 

Yes exactly the demo will go in FreeRTOS/FreeRTOS git which has separate git PRs. Though that PR will depend on these kernel changes to function appropriately.

**Comment by mbruno-xmos** [comment]
The "xcc" compiler is actually a fork of an old version of Clang. In fact our older xcore architecture was upstreamed and is officially supported by Clang. The current xcore200 architecture is not however, but it may be supported in the future as we are working on moving to the current version of Clang.

May I suggest ThirdParty/Clang/XCORE200  ?  or ThirdParty/XMOSClang/XCORE200 (similar to portable/ARMClang) ?

**Comment by dachalco** [comment]
I'm closing this out. Have requested XMOS open a new PR with the latest updates for their toolchain.

**Comment by dachalco** [comment]
@mbruno-xmos 

In retrospect, the initial closure was a mistake and contributed to confusion. I appreciate your patience despite this fumble.

Secondly, I received an email from you containing details I prefer to redact -- minor release info I wasn't sure I could relay over Git. My response included an explanation for the previous closure but I'm unsure whether you received it so I paraphrase it:

> We want an XCORE port in `FreeRTOS/`. Going forward, let's use Git for discussion for others' context -- minor xmos release info -- For various reasons it's best if you or another XCORE expert opens the Git PR. Given that, I'm going to close my PR, can you open a new one?

**Pull request closed without merging**
