### PR TITLE
Synopsys ARC port, adding support for ARC EM and HS cores -- continued from PR #8.

### PR DESCRIPTION
**Pull request by yuhui-zheng**
Since https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/8 does not have "allow edits from maintainers" enabled, I'm proposing edits in this draft PR. 

Changes:
- Rebase.
- Move ```./portable/Synopsys/ARC``` to ```./portable/ThirdParty/GCC/ARC_EM_HS```, since our folder structure as of now is ```./portable/<compiler>/<architecture>```. 

There's no change to source code.

### CODE REVIEW

**Comment by YuguoWH** [comment]
Thank you for the review, I'm ok with this file structure. Actually the ARC port support GCC and MetaWare toolchains, so I'm not sure whether another folder is needed, like ./portable/ThirdParty/MetaWare/ARC_EM_HS

**Comment by yuhui-zheng** [comment]
@YuguoWH 

I've checked current status for embARC support in FreeRTOS -- https://www.freertos.org/a00090.html#ARC, one option for people land there is to go to your site to obtain the code along with further instructions at https://embarc.org/iot.html. I believe even after merging this PR we would still keep reference to your site at least. So if your site has specific instructructions on MetaWare, we may be fine there. 

Another thought is we may not have MetaWare compiler setup in our CI, so we won't be able to test that. I'll forward this discussion to folks, and if it's needed let's have another PR dedicated for MetaWare. (I did find two forms of user agreements at the bottom of this page https://www.synopsys.com/dw/ipdir.php?ds=sw_metaware. May need to go through approval process for setting up.) 

Action items for me:
- Close PR #7  from you, and make this draft PR an official PR. 
- I'll need one more approval from folks for this PR before merging.
- Will forward discussion for MetaWare.

One question for you:
- Do you happen to plan to submit a demo project for your port? (It'll be helpful to embARC users landing on FreeRTOS, they could jump start with a working project.)

**Comment by YuguoWH** [comment]
Thank you for your advice, I think we can focus on GCC in this PR. 
And for your questions:
> - Out of curiosity, do GCC and MetaWare compile the same source files for a port (e.g. the files in this PR), or does MetaWare need to have minor changes to files in this PR?

Yes, there are some macros to seperate compiler specific code so both compilers can work on the same code

> - Do you happen to plan to submit a demo project for your port? (It'll be helpful to embARC users landing on FreeRTOS, they could jump start with a working project.)

Sure, I'll prepare a demo project asap

**Comment by yuhui-zheng** [comment]
@YuguoWH We are going to merge this PR first. Whenever you get a chance for out-of-box project, happy to take a look. That'll give users an easy starting point. Thanks again for this PR, and hopefully we'll hear from you soon.

**Pull request merged**
