### PR TITLE
Xtensa support updated and moved to Partner-Supported submodules

### PR DESCRIPTION
**Pull request by ianstcdns**
Remove legacy Xtensa port; leave README with pointer to latest partner-maintained code

Description
-----------
The Xtensa FreeRTOS port has been consolidated in the Partner-Supported submodules, along with numerous updates and bug-fixes.
The old location now contains a README indicating where to find the latest version of the Xtensa port and test code.

Test Steps
-----------
- Tested via various demo and stress tests as provided through the Partner-Supported-Demos submodule.
- Regression testing on many different LX7, LX8, and NX configurations.

Checklist:
----------

- [ x ] I have tested my changes. No regression in existing tests.
- [ x ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------
N/A

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ianstcdns** [comment]
@aggarg @RichardBarry

Submitting updated Xtensa port to FreeRTOS v11

I've created pull requests for Cadence's updated Xtensa FreeRTOS port and demo code.  As you recommended, we have moved it to the Partner-Supported-Ports and Partner-Supported-Demos submodules, removed out-of-date code from the higher-level repos, and left a couple of READMEs in the old locations indicating the new home for this code.

Thank you in advance for your help reviewing this upstream request.

**Comment by cookpate** [comment]
FreeRTOS/FreeRTOS-Kernel-Partner-Supported-Ports#15 has been merged. Could you move the submodule pointer?
```diff
diff --git a/portable/ThirdParty/Partner-Supported-Ports b/portable/ThirdParty/Partner-Supported-Ports
index dc3afc6e8..abc22103e 160000
--- a/portable/ThirdParty/Partner-Supported-Ports
+++ b/portable/ThirdParty/Partner-Supported-Ports
@@ -1 +1 @@
-Subproject commit dc3afc6e837426b4bda81bbb6cf45bfb6f34c7e9
+Subproject commit abc22103e1e6634b33457d4127bff1ab62f27f90
```

**Comment by ianstcdns** [comment]
Thank you for the quick review and merge.  I've updated the Partner-Supported-Ports submodule pointer.

**Review by aggarg — APPROVED** [review]

**Comment by aggarg** [comment]
@ianstcdns Please sync with the latest main branch.

**Comment by ianstcdns** [comment]
Thanks, @aggarg.  Rebased on top of main.  Is it best to squash the 2 commits or to leave them separate?

**Review by rawalexe — APPROVED** [review]

**Pull request merged**
