### PR TITLE
Posix: fix build failure

### PR DESCRIPTION
**Pull request by twpedersen**
Fixes: a48f137896b9 ("Posix Port: Comment and remove unused variables (#230)")

The above commit introduced the compile error:

```
/FreeRTOS/FreeRTOS/Source/portable/ThirdParty/GCC/Posix/port.c: In function ‘prvSetupSignalsAndSchedulerPolicy’:
/FreeRTOS/FreeRTOS/Source/portable/ThirdParty/GCC/Posix/port.c:528:28: error: incompatible type for argument 3 of ‘pthread_sigmask’
                            *&xSchedulerOriginalSignalMask );
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/signal.h:359,
                 from FreeRTOS/FreeRTOS/Source/portable/ThirdParty/GCC/Posix/port.c:53:
/usr/include/x86_64-linux-gnu/bits/sigthread.h:33:31: note: expected ‘__sigset_t * restrict’ {aka ‘struct <anonymous> * restrict’} but argument is of type ‘sigset_t’ {aka ‘struct <anonymous>’}
        __sigset_t *__restrict __oldmask)__THROW;
```

### CODE REVIEW

**Comment by twpedersen** [comment]
What is the failing check?

```
File Delta: portable/ThirdParty/GCC/Posix/port.c
11
--- 
12
 +++ 
13
 @@ -1,5 +1,5 @@
14
  /*
15
 - * FreeRTOS Kernel V10.4.3
16
 + * FreeRTOS Kernel V10.4.2
17
   * Copyright (C) 2020 Amazon.com, Inc. or its affiliates.  All Rights Reserved.
18
   *
19
   * Permission is hereby granted, free of charge, to any person obtaining a copy of
20
```

**Comment by dachalco** [comment]
Hi @twpedersen 

A subset of the repo's files require a FreeRTOS Kernel Header (version + copyright + license). 
During a PR we make sure these files remain consistent and up to date.
I merged `upstream/main` so it would use the recently updated check and the check passes.

**Comment by twpedersen** [comment]
Thank you.

**Comment by twpedersen** [comment]
@alfred2g @cobusve can you please take a look?

**Comment by twpedersen** [comment]
is there no interest in fixing a build failure in the LTS release, or am I the only one seeing this?

**Review by alfred2g — APPROVED** [review]

**Review by cobusve — APPROVED** [review]

**Comment by alfred2g** [comment]
> @alfred2g @cobusve can you please take a look?

we have 3 similar PR's, we are fixing an issue with the checks, I will ask so they are overridden.
Thanks for the PR :)

**Comment by twpedersen** [comment]
Thanks guys :pray:

**Pull request merged**
