### PR TITLE
Wsign-conversion CFLAG compatibility

### PR DESCRIPTION
**Pull request by hmalpani**
WSign-conversion CFLAG compatibility

Description
These changes are required else build warnings occurs when building with Wsign-conversion CFLAG

Test Steps

Related Issue

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aggarg** [comment]
Which port are you seeing these warnings on?

**Comment by aggarg** [comment]
I think it should be fixed in the xtensa port layer. Try changing the return type of [this function](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/portable/ThirdParty/XCC/Xtensa/portmacro.h#L99) to `UBaseType_t`.

**Comment by alfred2g** [comment]
Closing this PR for inactivity, please reopen when ready to make the recommended modifications

**Pull request closed without merging**
