### PR TITLE
Add option to keep the main stack intact on CM7

### PR DESCRIPTION
**Pull request by HazardyKnusperkeks**
Description
-----------
Add an option to keep the main stack intact.

Test Steps
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by HazardyKnusperkeks** [comment]
Is this something which will be considered?

**Comment by aggarg** [comment]
Do you have a use case for this?

**Comment by HazardyKnusperkeks** [comment]
> Do you have a use case for this? The reason I ask is because all of our port do this and this is a well known behavior.

Maybe well known, but not well documented. I was not aware of it, and I thought I've read a lot about FreeRTOS before using it the first time. And it costed me some hours and a bit sanity.

My use case are constructors. They shall only run when the main has started in a well defined order.
I can work around this stuff, and I can also work around the stack pointer setting.

**Comment by HazardyKnusperkeks** [comment]
> > Do you have a use case for this? The reason I ask is because all of our port do this and this is a well known behavior.
> 
> Maybe well known, but not well documented. I was not aware of it, and I thought I've read a lot about FreeRTOS before using it the first time. And it costed me some hours and a bit sanity.
> 
> My use case are constructors. They shall only run when the main has started in a well defined order. I can work around this stuff, and I can also work around the stack pointer setting.

I work around by setting the stack pointer in the vector table to the value directly before `vTaskStartScheduler`.

**Comment by aggarg** [comment]
You can look at [vApplicationDaemonTaskStartupHook ](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/timers.c#L756-L764) also.

**Pull request closed without merging**
