### PR TITLE
Add Trace Hook Macros to all API calls

### PR DESCRIPTION
**Pull request by Techcore123**
Add Trace Hook Macros to all API calls

Description
-----------
This pull-request adds out-of-the-box support for different tracing tools.
For more information see following forum post: https://forums.freertos.org/t/add-tracing-functionality-for-all-api-calls/18007.

New trace hook macros have been added for all public API functions, one for each function entry and one for each exit.
There are no functional changes, as the macros are by default empty.

Test Steps
-----------
N/A

Checklist:
----------
- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rawalexe** [comment]
Thank you for your contribution. I have informed team about your PR and the subject matter expert will be reviewing it soon. 

Thank you for your patience.

**Comment by archigup** [comment]
Is this intended just for user code to kernel code transitions? In that case it could also potentially be implemented by wrapping FreeRTOS API functions with a macro that adds tracing code; this would also catch code in return statements.

For example:

```c
#include "FreeRTOS.h"
#include "task.h"

BaseType_t trace_xTaskDelayUntil( TickType_t *pxPreviousWakeTime,
                                                               const TickType_t xTimeIncrement )
{
    BaseType_t returnVal;
    // entry trace code
    returnVal = xTaskDelayUntil( pxPreviousWakeTime, xTimeIncrement );
    // exit trace code
    return returnVal;
}

#define xTaskDelayUntil trace_xTaskDelayUntil
```

That could potentially be put in a wrapper header or something similar.

Not advocating for either solution, but would like to understand the options that are on the table, and what factors we need to consider.

**Comment by rawalexe** [comment]
Hello @Techcore123,
Can you please provide a test document, showing that there are no spelling errors on parameters for the trace defined functions and match their `ifndef` and code implementation

**Comment by Techcore123** [comment]
Hi @rawalexe,
Such a document does not exist yet, but could of course be created.
Are there any guidelines or an example?

**Comment by rawalexe** [comment]
Hello @Techcore123 ,
The easiest document will be a demo that implements these traces, if that's a feasable option for you.

Best Regards,
Anubhav Rawal

**Comment by aggarg** [comment]
I did the following changes:

1. Wrote a script to find public APIs which did not have trace macros and added those.
2. Wrote a script to find APIs which were passing wrong parameters and fixed those. 
3. Tested by enabling all the config options. 

Here are the scripts that I wrote - [Scripts.zip](https://github.com/FreeRTOS/FreeRTOS-Kernel/files/12660826/Scripts.zip)

**Review by aggarg — APPROVED** [review]

**Review by shubnil — APPROVED** [review]

**Pull request merged**
