### PR TITLE
Synopsys ARC port, adding support for ARC EM and HS cores

### PR DESCRIPTION
**Pull request by YuguoWH**
Synopsys ARC port of FreeRTOS kernel.

### CODE REVIEW

**Comment by RichardBarry** [comment]
Thanks for your submission.  Are you from Synopsys?  I note there are subtle differences between this pull request and the code here: https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_osp/releases including an update to the MIT license for the port layer hence the question.

**Comment by YuguoWH** [comment]
Hi @RichardBarry.  Yes I'm from Synopsys. After the OSP release you mentioned, we had some modifications to the embARC code and put it in embARC BSP, which you could find here: https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_bsp/tree/upstream
But basically not much has been changed in port layer. May I ask which license is required in FreeRTOS kernel?

**Comment by RichardBarry** [comment]
Thanks for the confirmation.  FreeRTOS is now MIT licensed - I note your website still has the old license.   You can of course license your port bits anyway you like, but we strongly encourage MIT to make the port layers license compatible with the rest of FreeRTOS, and to make it as easy for users to use in production as possible.

I've checked the code out and will look through it to put together some comments (such as moving to the third party directory, and also publishing a demo, etc.).  Then we can work to incorporating in the release.

Currently SourceForge/SVN is still used as the source of truth, so merges will be done there.  This repo is synced from there.  After the next release the intention is to switch, so this git repo becomes the source of truth, and code gets synced back to SVN.

**Comment by yuhui-zheng** [comment]
Hi @YuguoWH, 

It seems this PR has "allow edits from maintainers" disabled, so that I cannot update your PR directly. Instead, I'm proposing changes in this draft PR -- https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/28. 

Changes:
- Rebase 
- Move ```./portable/Synopsys/ARC``` to ```./portable/ThirdParty/GCC/ARC_EM_HS```, since our folder structure as of now is ```./portable/<compiler>/<architecture>```. (The "GCC" is concluded from your Travis CI config -- https://travis-ci.org/github/foss-for-synopsys-dwc-arc-processors/embarc_osp/builds/659363653/config.)

There's no source code change. Please let me know your thoughts.

**Comment by yuhui-zheng** [comment]
Moving further review to PR 28, so that I'm closing this PR.

**Pull request closed without merging**
