### PR TITLE
Check bit-2(SEL) of EXC_RETURN in PendSV_Handler() to determine if MC…

### PR DESCRIPTION
**Pull request by sgetz-ggr**
Check bit-2(SEL) of EXC_RETURN in PendSV_Handler() to determine if MCU should return to the main stack or process stack, otherwise the hard fault would occur.

Description
-----------
The Hard fault occurs when interrupts are triggered after peripherals' interrupts are ready, but vRestoreContextOfFirstTask() has not been invoked yet.

To avoid this situation, it is necessary to initialize the flag to FALSE. However, if we consider PendSV_Handler() as an independent module, a defect in PendSV_Handler() is present, where it returns to PSP (Process Stack Pointer) without checking the bit-2 (SEL). This can result in a hard fault if any interrupt is raised with incorrect usage of XXX_FromISR().

The detailed is as following:

In certain situations, the interrupt handler needs to utilize IPC (Inter-Process Communication) APIs to communicate with other processes via XXX_FromISR() and perform a context switch to a task with a higher or equal priority compared to the current task, relying on the flag returned by XXX_FromISR(). However, based on the implementation of XXX_FromISR(), the flag will only be set to TRUE within XXX_FromISR(). This means that if the flag is not initialized to FALSE before invoking XXX_FromISR(), an unexpected context switch may occur. Fortunately, in normal cases, the context switch does not have a fatal effect because there is at least one task in the ready list—the idle task (P.S. It is still a problem if the unexpected context switch occurs in the idle task, but it is a rare occurrence).

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] ~I have modified and/or added unit-tests to cover the code changes in this Pull Request.~

Related Issue
-----------
N/A.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aggarg** [comment]
> The Hard fault occurs when interrupts are triggered after peripherals' interrupts are ready, but vRestoreContextOfFirstTask() has not been invoked yet.

FreeRTOS divides interrupts into 2 parts - 
1. Interrupts with priority less than and equal to `configMAX_SYSCALL_INTERRUPT_PRIORITY` - these interrupts are masked until the scheduler is started and these are also masked in critical sections. The application can call `FromISR` APIs from these ISRs.
2. Interrupts with priority greater than `configMAX_SYSCALL_INTERRUPT_PRIORITY` - these interrupts are not masked by FreeRTOS and `FromISR` APIs cannot be called from these ISRs.

```

            Logical      Numerical
           Priorities    Priorities
           +--------+    +-------+             ^
           |        |    |       |             |
           |        |    |       |             |
           |        |    |       |             | Not masked by FreeRTOS kernel
           | Higher |    | Lower |             | ( FreeRTOS APIs can not be
           |        |    |       |             |    called from these ISRs. )
           |        |    |       |             |
           |        |    |       |             v
           +--------+    +-------+ <---------------- configMAX_SYSCALL_INTERRUPT_PRIORITY
           |        |    |       |             ^
           |        |    |       |             |
           |        |    |       |             |
           |        |    |       |             |
           |        |    |       |             |
           |        |    |       |             |
           |        |    |       |             |
           | Lower  |    |Higher |             | Masked by FreeRTOS Kernel
           |        |    |       |             | ( FreeRTOS APIs can be
           |        |    |       |             |    called from these ISRs. ) 
           |        |    |       |             |
           |        |    |       |             |
           |        |    |       |             |
           |        |    |       |             |
           |        |    |       |             |
           |        |    |       |             |
           +--------+    +-------+             v
```

It seems that you are calling a `FromISR` API from an interrupt of priority higher than `configMAX_SYSCALL_INTERRUPT_PRIORITY`. Is that right?

**Comment by sgetz-ggr** [comment]
> > The Hard fault occurs when interrupts are triggered after peripherals' interrupts are ready, but vRestoreContextOfFirstTask() has not been invoked yet.
> 
> FreeRTOS divides interrupts into 2 parts -
> 
> 1. Interrupts with priority less than and equal to `configMAX_SYSCALL_INTERRUPT_PRIORITY` - these interrupts are masked until the scheduler is started and these are also masked in critical sections. The application can call `FromISR` APIs from these ISRs.
> 2. Interrupts with priority greater than `configMAX_SYSCALL_INTERRUPT_PRIORITY` - these interrupts are not masked by FreeRTOS and `FromISR` APIs cannot be called from these ISRs.
> 
> It seems that you are calling a `FromISR` API from an interrupt of priority higher than `configMAX_SYSCALL_INTERRUPT_PRIORITY`. Is that right?

@aggarg Thanks for your clear explanation. You're absolutely right that the interrupt priority is higher than `configMAX_SYSCALL_INTERRUPT_PRIORITY`. However, based on my understanding, all hardware interrupts should take precedence over system call interrupts (such as PendSV and Systick for context switch), and these hardware interrupts can be raised at any time, regardless of whether the scheduler has started or not.

Therefore, what I'm currently considering is how we handle interrupts before the scheduler begins. In this scenario, we shouldn't set `PSP` to `sp` because `PSP` is zero. Instead, we need to check bit-2 (SEL) of EXC_RETURN to determine whether `PSP` or `MSP` should be moved to `sp`.

**Comment by aggarg** [comment]
> However, based on my understanding, all hardware interrupts should take precedence over system call interrupts (such as PendSV and Systick for context switch), and these hardware interrupts can be raised at any time, regardless of whether the scheduler has started or not.

This is not completely correct. You are right that PendSV should run at the lowest priority and we ensure that in the kernel. For the other hardware interrupts, you need to consider the following:
* If you want your interrupt to be not affected by FreeRTOS (i.e. it can fire before scheduler has started and it should not be masked during FreeRTOS critical sections), then you should set its priority higher than `configMAX_SYSCALL_INTERRUPT_PRIORITY`. Remember that you cannot call any FreeRTOS `FromISR` APIs from these ISRs.
* On the other hand, if you want to call FreeRTOS `FromISR` APIs from ISR, then you should set the interrupt's priority less than or equal to `configMAX_SYSCALL_INTERRUPT_PRIORITY`. Remember that these interrupts remain masked till the scheduler is started and they are also masked during FreeRTOS critical sections. 

> Therefore, what I'm currently considering is how we handle interrupts before the scheduler begins.

The interrupts that FreeRTOS care about, are not supposed to fire before the scheduler has started. 

> In this scenario, we shouldn't set PSP to sp because PSP is zero. Instead, we need to check bit-2 (SEL) of EXC_RETURN to determine whether PSP or MSP should be moved to sp.

PendSV must not fire before the scheduler has started as context switching does not make any sense before scheduler is started.

I think you are either manipulating BASEPRI directly or setting up your interrupt priorities incorrectly. If you share more about the problem that you are facing and possibly show some code, I can try to suggest a solution.

**Comment by sgetz-ggr** [comment]
> 
> I think you are either manipulating BASEPRI directly or setting up your interrupt priorities incorrectly. If you share more about the problem that you are facing and possibly show some code, I can try to suggest a solution.

Yes, it's a good idea, here we go and **I'll mark some description as bold for highlight**:

* License Clause
```c
  /**
  * @attention
  *
  * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
  * All rights reserved.</center></h2>
  *
  * This software component is licensed by ST under BSD 3-Clause license,
  * the "License"; You may not use this file except in compliance with the
  * License. You may obtain a copy of the License at:
  *                        opensource.org/licenses/BSD-3-Clause
  *
  */

````
* main function
    * The MCU is initialized, and GPIO interrupts are enabled before the scheduler starts.
    * **The MCU's global interrupt is enabled in `vStartFirstTask()`**, which is invoked by `osKernelStart()`.
    * The details of `vStartFirstTask()` will be provided later.
```c
int main(void)
{
  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config();

  /* Initialize all configured peripherals */
/* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOE_CLK_ENABLE();
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOH_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
  __HAL_RCC_GPIOD_CLK_ENABLE();

  HAL_NVIC_SetPriority(EXTI9_IRQn, 5, 0);
  HAL_NVIC_EnableIRQ(EXTI9_IRQn);


  /* Init scheduler */
  osKernelInitialize();  /* Call init function for freertos objects (in freertos.c) */
  MX_FREERTOS_Init();
  /* Start scheduler */
  osKernelStart(); /*  invoke  vStartFirstTask() here      */

  /* We should never get here as control is now taken by the scheduler */
  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}
````
* `vStartFirstTask()`
    * Set the Main Stack Pointer (MSP) and enable global interrupts, **then trigger the `SVCHandler()` function to set the Process Stack Pointer (PSP)**.
```c
void vStartFirstTask( void ) /* __attribute__ (( naked )) PRIVILEGED_FUNCTION */
{
        __asm volatile
        (
        "       ldr r0, xVTORConst                                                              \n" /* Use the NVIC offset register to locate the stack. */
        "       ldr r0, [r0]                                                                    \n" /* Read the VTOR register which gives the address of vector table. */
        "       ldr r0, [r0]                                                                    \n" /* The first entry in vector table is stack pointer. */
        "       msr msp, r0                                                                             \n" /* Set the MSP back to the start of the stack. */
        "       cpsie i                                                                                 \n" /* Globally enable interrupts. */
        "       cpsie f                                                                                 \n"
        "       dsb                                                                                             \n"
        "       isb                                                                                             \n"
        "       svc %0                                                                                  \n" /* System call to start the first task. */
        "       nop                                                                                             \n"
        "                                                                                                       \n"
        "   .align 4                                                                            \n"
        "xVTORConst: .word 0xe000ed08                                           \n"
        :: "i" ( portSVC_START_SCHEDULER ) : "memory"
        );
}
```
* `SVC_Handler()`
```c
void SVC_Handler( void ) /* __attribute__ (( naked )) PRIVILEGED_FUNCTION */
{
        __asm volatile
        (
        "       tst lr, #4                                                                              \n"
        "       ite eq                                                                                  \n"
        "       mrseq r0, msp                                                                   \n"
        "       mrsne r0, psp                                                                   \n"
        "       ldr r1, svchandler_address_const                                \n"
        "       bx r1                                                                                   \n"
        "                                                                                                       \n"
        "       .align 4                                                                                \n"
        "svchandler_address_const: .word vPortSVCHandler_C      \n"
        );
}
```

* The interrrupt handler
    * If xHigherPriorityTaskWoken is **NOT** FALSE, trigger the PendSV` interrupt to perform a context switch. However, in my case, **xHigherPriorityTaskWoken is uninitialized and may contain a floating value**.
    * `portDISABLE_INTERRUPTS()` and `portENABLE_INTERRUPTS()` are implemented of ARM instruction.
    * **If an interrupt handler is fired before the `SVC_handler()` is triggered, a hard fault may occur because the Process Stack Pointer (PSP) is uninitialized, resulting in a value of zero.**
```c
#define portEND_SWITCHING_ISR( xSwitchRequired )                        if( xSwitchRequired ) portNVIC_INT_CTRL_REG = portNVIC_PENDSVSET_BIT
#define portYIELD_FROM_ISR( x )                                                         portEND_SWITCHING_ISR( x )
#define portDISABLE_INTERRUPTS()                                                        __asm volatile ( " cpsid i " ::: "memory" )
#define portENABLE_INTERRUPTS()                                                         __asm volatile ( " cpsie i " ::: "memory" )

void probe_isr_callback(board_event_t source_id, uint32_t instance_id)
{
    /* Send irq number */
    BaseType_t xHigherPriorityTaskWoken;
    if (xTaskNotifyFromISR(pHandle, notify_val,
                            eAction, &xHigherPriorityTaskWoken)!= pdPASS) {
        return false;
    }
    portYIELD_FROM_ISR( xHigherPriorityTaskWoken );

    bat_in[instance_id] = source_id == BOARD_EVENT_BAT_IN ? true : false;
}
```

**Comment by sgetz-ggr** [comment]
> > If an interrupt handler is fired before the SVC_handler() is triggered, a hard fault may occur because the Process Stack Pointer (PSP) is uninitialized, resulting in a value of zero.
> 
> The point is `probe_isr_callback` must not fire before the scheduler is started as it calls FreeRTOS APIs.
> 
In fact, `probe_isr_callback` DOES fire within a brief period after the ` vStartFirstTask()` is executing `cpsie i` assembly instruction.(The implementation of `vStartFirstTask()` has been provided in https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/699#issuecomment-1621043296)

> I assume `probe_isr_callback` is related to `EXTI9_IRQn` and the value of `configMAX_SYSCALL_INTERRUPT_PRIORITY` is 5 (shifted as per the number of priority bits implemented). Please confirm if these assumptions are correct. Assuming they are correct, you should move the code to enable `EXTI9_IRQn` a bit later:
> 
I agree enabling `EXTI9_IRQn` later can prevent the occurrence of a hard fault, and it has been successful in my testing. However, I am also considering how to ensure that FreeRTOS does not get stuck even if developers make incorrect implementations, that's why I provide this fixing.:blush:

**Comment by aggarg** [comment]
> However, I am also considering how to ensure that FreeRTOS does not get stuck even if developers make incorrect implementations.

The way we have try to do that is by disabling interrupts as soon as you call any FreeRTOS API and only enable them when the scheduler starts. The PendSV handler executes on every context switch and therefore, needs to be very efficient. That is why I do not think we should add this code.

**Comment by sgetz-ggr** [comment]
> 
> The way we have try to do that is by disabling interrupts as soon as you call any FreeRTOS API and only enable them when the scheduler starts. The PendSV handler executes on every context switch and therefore, needs to be very efficient. That is why I do not think we should add this code.

I understand  your concern, but when comparing it to the `bl vTaskSwitchContext` in `PendSV()`, which involves branching to C code, don't you think adding four atomic instructions is a reasonable cost to ensure system robustness?

**Comment by RichardBarry** [comment]
> However, I am also considering how to ensure that FreeRTOS does not get stuck even if developers make incorrect implementations.

Our policy, from very early days when interrupts trying to use the scheduler before the scheduler was running was a primary cause of confusing support requests, is to do the opposite.  1) Try to avoid users making common errors (in this case, by ensuring interrupt priorities from which it is valid to make kernel calls are disabled between the first call to a kernel API and the kernel starting), and 2) Alert users to mistakes at the first opportunity (ensuring latent bugs don't get past early development stages, or cause issues at a time other than at the cause of the error).

**Comment by aggarg** [comment]
> but when comparing it to the bl vTaskSwitchContext in PendSV(), which involves branching to C code, don't you think adding four atomic instructions is a reasonable cost to ensure system robustness?

As Richard mentioned, trying to use the scheduler from ISR (i.e. trying to call a `FromISR` API) before the scheduler is started, is basically trying to use APIs which depend on the internal scheduler state before the state is initialized properly - It is incorrect by design. The current proposed change imposes a penalty of 4 instructions every context switch on all the correct applications just to avoid fault in an incorrect application. I think fixing the application is the right thing to do in this case.

**Comment by sgetz-ggr** [comment]
> 1) Try to avoid users making common errors (in this case, by ensuring interrupt priorities from which it is valid to make kernel calls are disabled between the first call to a kernel API and the kernel starting), and 2) Alert users to mistakes at the first opportunity (ensuring latent bugs don't get past early development stages, or cause issues at a time other than at the cause of the error).

@RichardBarry, Thank you for providing me with the historical background. I agree with your second point, which emphasizes the importance of alerting users to any defects at an early stage. However, it's worth noting that not all mistakes are easily triggered, especially when they need to occur within a very short timeframe, as in the case of this issue. Therefore, it would be beneficial if we can bypass any unstable states before the scheduler starts. While it's good for developers to be aware that certain actions should not be taken before the system is ready, we can also take measures to make the system more fault-tolerant and resilient to such scenarios.

> 
> As Richard mentioned, trying to use the scheduler from ISR (i.e. trying to call a `FromISR` API) before the scheduler is started, is basically trying to use APIs which depend on the internal scheduler state before the state is initialized properly - It is incorrect by design. The current proposed change imposes a penalty of 4 instructions every context switch on all the correct applications just to avoid fault in an incorrect application. I think fixing the application is the right thing to do in this case.

@aggarg, theoretically, adding an additional 4 instructions will introduce some overhead. However, when comparing it to the total number of instructions in the PendSV routine, which is 102 as shown below:

Total instructions in PendSV: 102

The ratio of 4 instructions to 102 instructions is approximately 3.92%. Considering this relatively small percentage, can't we just ignore it?
```c
void PendSV_Handler( void ) /* __attribute__ (( naked )) PRIVILEGED_FUNCTION */
{
 8013950:       f3ef 8009       mrs     r0, PSP
 8013954:       f3ef 820b       mrs     r2, PSPLIM
 8013958:       4673            mov     r3, lr
 801395a:       e920 0ffc       stmdb   r0!, {r2, r3, r4, r5, r6, r7, r8, r9, sl, fp}
 801395e:       4a08            ldr     r2, [pc, #32]   ; (8013980 <pxCurrentTCBConst>)
 8013960:       6811            ldr     r1, [r2, #0]
 8013962:       6008            str     r0, [r1, #0]
 8013964:       b672            cpsid   i
 8013966:       f7fe fcef       bl      8012348 <vTaskSwitchContext>
 801396a:       b662            cpsie   i
 801396c:       4a04            ldr     r2, [pc, #16]   ; (8013980 <pxCurrentTCBConst>)
 801396e:       6811            ldr     r1, [r2, #0]
 8013970:       6808            ldr     r0, [r1, #0]
 8013972:       e8b0 0ffc       ldmia.w r0!, {r2, r3, r4, r5, r6, r7, r8, r9, sl, fp}
 8013976:       f382 880b       msr     PSPLIM, r2
 801397a:       f380 8809       msr     PSP, r0
 801397e:       4718            bx      r3
}

08012348 <vTaskSwitchContext>:
{
 8012348:       b5f0            push    {r4, r5, r6, r7, lr}
 801234a:       4b31            ldr     r3, [pc, #196]  ; (8012410 <vTaskSwitchContext+0xc8>)
 801234c:       b085            sub     sp, #20
 801234e:       681a            ldr     r2, [r3, #0]
 8012350:       4b30            ldr     r3, [pc, #192]  ; (8012414 <vTaskSwitchContext+0xcc>)
 8012352:       b11a            cbz     r2, 801235c <vTaskSwitchContext+0x14>
 8012354:       2201            movs    r2, #1
 8012356:       601a            str     r2, [r3, #0]
 8012358:       b005            add     sp, #20
 801235a:       bdf0            pop     {r4, r5, r6, r7, pc}
 801235c:       4d2e            ldr     r5, [pc, #184]  ; (8012418 <vTaskSwitchContext+0xd0>)
 801235e:       601a            str     r2, [r3, #0]
 8012360:       682b            ldr     r3, [r5, #0]
 8012362:       6b1b            ldr     r3, [r3, #48]   ; 0x30
 8012364:       681a            ldr     r2, [r3, #0]
 8012366:       f1b2 3fa5       cmp.w   r2, #2779096485 ; 0xa5a5a5a5
 801236a:       d10b            bne.n   8012384 <vTaskSwitchContext+0x3c>
 801236c:       685a            ldr     r2, [r3, #4]
 801236e:       f1b2 3fa5       cmp.w   r2, #2779096485 ; 0xa5a5a5a5
 8012372:       d107            bne.n   8012384 <vTaskSwitchContext+0x3c>
 8012374:       689a            ldr     r2, [r3, #8]
 8012376:       f1b2 3fa5       cmp.w   r2, #2779096485 ; 0xa5a5a5a5
 801237a:       d103            bne.n   8012384 <vTaskSwitchContext+0x3c>
 801237c:       68db            ldr     r3, [r3, #12]
 801237e:       f1b3 3fa5       cmp.w   r3, #2779096485 ; 0xa5a5a5a5
 8012382:       d004            beq.n   801238e <vTaskSwitchContext+0x46>
 8012384:       6828            ldr     r0, [r5, #0]
 8012386:       6829            ldr     r1, [r5, #0]
 8012388:       3134            adds    r1, #52 ; 0x34
 801238a:       f7f3 f9f1       bl      8005770 <vApplicationStackOverflowHook>
 801238e:       4b23            ldr     r3, [pc, #140]  ; (801241c <vTaskSwitchContext+0xd4>)
 8012390:       f04f 0c14       mov.w   ip, #20
 8012394:       461f            mov     r7, r3
 8012396:       4e22            ldr     r6, [pc, #136]  ; (8012420 <vTaskSwitchContext+0xd8>)
 8012398:       6834            ldr     r4, [r6, #0]
 801239a:       fb0c f204       mul.w   r2, ip, r4
 801239e:       5898            ldr     r0, [r3, r2]
 80123a0:       1899            adds    r1, r3, r2
 80123a2:       b188            cbz     r0, 80123c8 <vTaskSwitchContext+0x80>
 80123a4:       6848            ldr     r0, [r1, #4]
 80123a6:       3208            adds    r2, #8
 80123a8:       6840            ldr     r0, [r0, #4]
 80123aa:       4413            add     r3, r2
 80123ac:       4298            cmp     r0, r3
 80123ae:       bf08            it      eq
 80123b0:       6843            ldreq   r3, [r0, #4]
 80123b2:       6048            str     r0, [r1, #4]
 80123b4:       bf08            it      eq
 80123b6:       604b            streq   r3, [r1, #4]
 80123b8:       2314            movs    r3, #20
 80123ba:       fb03 7304       mla     r3, r3, r4, r7
 80123be:       685b            ldr     r3, [r3, #4]
 80123c0:       68db            ldr     r3, [r3, #12]
 80123c2:       602b            str     r3, [r5, #0]
 80123c4:       6034            str     r4, [r6, #0]
 80123c6:       e7c7            b.n     8012358 <vTaskSwitchContext+0x10>
 80123c8:       bb04            cbnz    r4, 801240c <vTaskSwitchContext+0xc4>
 80123ca:       4b16            ldr     r3, [pc, #88]   ; (8012424 <vTaskSwitchContext+0xdc>)
 80123cc:       4d16            ldr     r5, [pc, #88]   ; (8012428 <vTaskSwitchContext+0xe0>)
 80123ce:       9301            str     r3, [sp, #4]
 80123d0:       f640 33b7       movw    r3, #2999       ; 0xbb7
 80123d4:       21ff            movs    r1, #255        ; 0xff
 80123d6:       4a15            ldr     r2, [pc, #84]   ; (801242c <vTaskSwitchContext+0xe4>)
 80123d8:       9300            str     r3, [sp, #0]
 80123da:       4628            mov     r0, r5
 80123dc:       4b14            ldr     r3, [pc, #80]   ; (8012430 <vTaskSwitchContext+0xe8>)
 80123de:       f004 fa8d       bl      80168fc <snprintf_>
 80123e2:       28fe            cmp     r0, #254        ; 0xfe
 80123e4:       bf8c            ite     hi
 80123e6:       2324            movhi   r3, #36 ; 0x24
 80123e8:       542c            strbls  r4, [r5, r0]
 80123ea:       9003            str     r0, [sp, #12]
 80123ec:       480e            ldr     r0, [pc, #56]   ; (8012428 <vTaskSwitchContext+0xe0>)
 80123ee:       bf84            itt     hi
 80123f0:       f885 30fe       strbhi.w        r3, [r5, #254]  ; 0xfe
 80123f4:       f885 40ff       strbhi.w        r4, [r5, #255]  ; 0xff
 80123f8:       f00a fbfa       bl      801cbf0 <ggr_bp_manager_print>
 80123fc:       490a            ldr     r1, [pc, #40]   ; (8012428 <vTaskSwitchContext+0xe0>)
 80123fe:       aa03            add     r2, sp, #12
 8012400:       2003            movs    r0, #3
 8012402:       f01b fc41       bl      802dc88 <ggr_llevel_debug_record>
 8012406:       f01b fd1b       bl      802de40 <ggr_llevel_debug_save>
 801240a:       e7fe            b.n     801240a <vTaskSwitchContext+0xc2>
 801240c:       3c01            subs    r4, #1
 801240e:       e7c4            b.n     801239a <vTaskSwitchContext+0x52>

```

**Comment by aggarg** [comment]
It is not only about the overhead it is but the usefulness of it too. Even if you added this change and not fixed the root cause in your application, you very likely will crash anywhere else depending on how long the interrupts are incorrectly left enabled. So all it achieves is masking the real problem for a very corner case and that is why, I am not in favor of it.

**Comment by sgetz-ggr** [comment]
> It is not only about the overhead but also the usefulness of it. Even if you added this change and not fixed the root cause in your application, you very likely will crash anywhere else depending on how long the interrupts are incorrectly left enabled. So all it achieves is masking the real problem for a very corner case and that is why, I am not in favor of it.

**Comment by sgetz-ggr** [comment]
> > It is not only about the overhead but also the usefulness of it. Even if you added this change and not fixed the root cause in your application, you very likely will crash anywhere else depending on how long the interrupts are incorrectly left enabled. So all it achieves is masking the real problem for a very corner case and that is why, I am not in favor of it.

I would appreciate it if you could review the modifications I have made. They are not without their merits.

When an exception is triggered, the lr register indicates to the MCU whether it should return to the PSP or MSP stack based on bit[2]. In the original implementation, PendSV loads the PSP directly into the SP without checking the bits. **If we consider this individually, it is a logical error** that I couldn't resist correcting.

I understand that we can prevent this issue at the application level, but I believe the system would be better if we address it directly.

**Comment by aggarg** [comment]
I have already reviewed your change and that is how I could help you to point the issue in your application. 

> When an exception is triggered, the lr register indicates to the MCU whether it should return to the PSP or MSP stack based on bit[2].

You are exactly right. 

>  In the original implementation, PendSV loads the PSP directly into the SP without checking the bits. If we consider this individually, it is a logical error that I couldn't resist correcting.

It would be an error if PendSV was designed to fire before  the scheduler is started which is not the case. 

> I understand that we can prevent this issue at the application level, but I believe the system would be better if we address it directly.

Please try to understand that adding this check does not solve the problem but just masks the application bug only. Let me try to explain with another example. Consider the following code - 

```c
QueueHandle_t xQueue;

int main( void )
{
    /* Setup and enable timer interrupt. */
    vSetupTimerInterrupt();

    /* Create a queue capable of holding 5 uint32_t. */
    xQueue = xQueueCreate( 5, sizeof( uint32_t ) );

    /* Create a task aht will receive data from the queue. */
    xTaskCreate( prvReceiverTask, "Receiver", configMINIMAL_STACK_SIZE, NULL, tskIDLE_PRIORITY, NULL );

    vTaskStartScheduler();
}

void TimerISR( void )
{
    BaseType_t xHigherPriorityTaskWoken = pdFALSE;
    uint32_t valueToSend = 5;

    xQueueSendFromISR( xQueue, &( valueToSend ), &( xHigherPriorityTaskWoken ) );

    portYIELD_FROM_ISR( xHigherPriorityTaskWoken );
}
```

In this scenario, the timer interrupt will likely access `xQueue` before it is created. Do you see that the check you mentioned does not help in this case?

**Comment by sgetz-ggr** [comment]
> > I understand that we can prevent this issue at the application level, but I believe the system would be better if we address it directly.
> 
> 
> In this scenario, the timer interrupt will likely access `xQueue` before it is created and either trigger an assert of result in de-referencing NULL pointer. Do you see that the check you mentioned does not help in this case?

Your example is due to defact in ISR, but my example is due to exception return. And the NULL access isn't be intruduced by my patch.

> I have already reviewed your change and that is how I could help you to point the issue in your application.
> 
> > When an exception is triggered, the lr register indicates to the MCU whether it should return to the PSP or MSP stack based on bit[2].
> 
> You are exactly right.
> 
> > In the original implementation, PendSV loads the PSP directly into the SP without checking the bits. If we consider this individually, it is a logical error that I couldn't resist correcting.
> 
> It would be an error if PendSV was designed to fire before the scheduler is started which is not the case.
> 

It seems that you agree that it is an error but can be resolved at the application level. I respect your perspective, but perhaps we can consider adding some comments in the PendSV code to explain why we are not checking bit[2] when loading the PSP into the SP. (Just my 2 cents)

**Comment by RichardBarry** [comment]
Interesting debate, I think the discussion has run its course.  @sgetz-ggr - Thanks for your contribution.  In this case I agree with [@aggarg](https://amzn-aws.slack.com/team/W0186TF1GAC).  The code is as it is intentionally, as per my previous post, and I don't feel it helpful to make a change that has the potential to encourage or otherwise hide usage errors.  The intended interrupt behaviour, including a separate system stack, is configured as the scheduler starts.  I'm closing this PR as I don't think furthering the conversation thread will introduce any new information, and we can open a PR for the suggested code comment.

**Comment by sgetz-ggr** [comment]
> Interesting debate, I think the discussion has run its course. @sgetz-ggr - Thanks for your contribution. In this case I agree with [@aggarg](https://amzn-aws.slack.com/team/W0186TF1GAC). The code is as it is intentionally, as per my previous post, and I don't feel it helpful to make a change that has the potential to encourage or otherwise hide usage errors. The intended interrupt behaviour, including a separate system stack, is configured as the scheduler starts. I'm closing this PR as I don't think furthering the conversation thread will introduce any new information, and we can open a PR for the suggested code comment.

Agree, and nice to talk to you guys @RichardBarry and @aggarg

**Pull request closed without merging**
