### PR TITLE
Added ability to change task notification index for streambuffers

### PR DESCRIPTION
**Pull request by glemco**
Description
-----------
This PR adds the modification described in https://forums.freertos.org/t/multiple-message-buffers-per-task-interferences/17663:
> The code change necessary to enable your scenario should be relatively simple though - adding a member to the stream buffer structure that holds the task notification index to use with that stream buffer, and a utility API that sets that index

In short, all calls to `xTaskNotify*` APIs are now using the `*Indexed` version and a new field was added to `StreamBuffer_t` to store the notification value used for that buffer.
Now, this value can be get and set using new functions (`uxStreamBufferGetStreamBufferNotificationIndex` and `vStreamBufferSetStreamBufferNotificationIndex`) to avoid changing the overall API.

Test Steps
-----------

* Create any stream buffer, by default this will use 0 (`tskDEFAULT_INDEX_TO_NOTIFY`) as index.
* Change the index using `vStreamBufferSetStreamBufferNotificationIndex`
  * Of course the configuration should allow this with a proper value of `configTASK_NOTIFICATION_ARRAY_ENTRIES`
  * The value must be changed before any task waits for the buffer, otherwise we may never wake them up
* Use the buffer as normal, it should block and resume as usual
* Sending a notification to the task to a different index should not wake up the task.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] I have modified and/or added unit-tests to cover the code changes in this Pull Request.
  * https://github.com/FreeRTOS/FreeRTOS/pull/1150

Related Issue
-----------

https://forums.freertos.org/t/multiple-message-buffers-per-task-interferences/17663

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by AniruddhaKanhere — APPROVED** [review]
Hello @glemco, thank you for taking the time to raise this pull request by following up on the forum post.

The change looks good to me and seems correct. I am approving this change in advance contingent on the fixing of the failing checks.

Thanks again!

**Comment by glemco** [comment]
Thanks @AniruddhaKanhere for the approval, I'm trying to figure out how to fix the failed steps, besides formatting which is trivial, I'm not quite sure why is the link verifier complaining and how to convince the coverage report that the functions are checked (or at least they should be in https://github.com/FreeRTOS/FreeRTOS/pull/1150, which obviously cannot be merged before this change in the kernel)

**Comment by AniruddhaKanhere** [comment]
Hey @glemco,

Apologies for the late response.

The link check issue seems to have been a transient failure. We are aware of this circular dependency between tests and the PR checks. We can ignore the failing unit tests for now.

Spell check is failing though. To fix that, you need to add the list of outlier spellings in [this](https://github.com/glemco/FreeRTOS-Kernel/blob/streambuffer_notification_index/.github/.cSpellWords.txt) file.

**Comment by glemco** [comment]
Thanks @AniruddhaKanhere for the explanation! It seems after your merge the spellcheck is not failing any more (probably another transient failure? It didn't seem related to the code I changed)
Does it mean this PR is now ready or is there anything else I could take care of?

**Comment by glemco** [comment]
Thanks @AniruddhaKanhere for the explanation! It seems after your merge the spellcheck is not failing any more (probably another transient failure? It didn't seem related to the code I changed)
Does it mean this PR is now ready or is there anything else I could take care of?

**Review by aggarg — APPROVED** [review]

**Review by AniruddhaKanhere — APPROVED** [review]

**Comment by AniruddhaKanhere** [comment]
Thank you for this PR @glemco and I apologize for the confusion with the checks. We are looking into what caused those transient failures. Maybe it was just that this branch was out of sync with the main repository.

Thank you @aggarg for the approval!

I shall be merging this PR now.

**Pull request merged**
