### PR TITLE
SMP: Add port local storage feature

### PR DESCRIPTION
**Pull request by Dazza0**
Description
-----------

The ESP-IDF port of FreeRTOS currently reserves a significant amount of space at the [start of a task's stack](https://github.com/espressif/esp-idf/blob/121ddb87e5130314e4fcc5e9cb260a81b7d30d36/components/freertos/port/xtensa/port.c#L142) to store some task specific data such as:

- FPU/Coprocessor context save area (for lazy context saving)
- Space for [GCC thread local storage variables](https://gcc.gnu.org/onlinedocs/gcc/Thread-Local.html)

The data above is accessed from assembly routines (e.g., during an exception or context switch) by either:

- Calculating a offset pointer to the data area base off of `pxTCB->pxEndOfStack`. This calculation of this offset can be tedious in assembly due to the lack of `sizeof()`.
- [In the case of the Xtensa port](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/9c048e0c71ee43630394981a86f5265bc57131e4/portable/ThirdParty/XCC/Xtensa/port.c#L215), it uses `pxTCB->xMPUSettings` to act as a pointer to those data areas as a workaround.

It would be easier if there was some way for ports to store arbitrary data directly in a task's TCB, thus can be easily accessed from variously assembly routines. Therefore, this PR proposes adding a new `pxTCB->xPortLocalStorage` entry who's size and type can be specified by the port. The Port Local Storage data is initialized by a hook function on task creation, and deinitialized on task deletion.

Some useful things that ports might want want to store a in the TCB include:

- Pointers to various FPU/Coprocessor register save areas
- Additional port specific run time stats information (e.g., total task cache miss cycles)
- List of opened resources (e.g., files) that can be shut auto-closed (e.g., from `portCLEAN_UP_TCB()`.

Test Steps
-----------

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by RichardBarry** [comment]
Can these be used for the same purpose? https://www.freertos.org/thread-local-storage-pointers.html

**Comment by Dazza0** [comment]
Hi @RichardBarry 

We had considered using TLSPs. This would entail each task initializing/deinitializing the TLSPs (and their associated memory) at the start/end of each task function. However, we found this approach to be unfeasible for the following reasons:

- Requiring each task to initialize/deinitialize TLSPs will a difficult requirement to propagate. IDF based applications (and IDF itself) will use third party libraries that are also FreeRTOS based. Thus, we will need to propagate this requirement to those libraries (i.e., apply patches on those libraries).
- Alternatively, we could also make it so that only tasks that require the local storage area (e.g., only tasks that use floating points) set the TLSPs. However, it is difficult for users to know whether a task will use floating points if their API call stack covers multiple third party libraries at different layers (i.e., protocol stack API calls).
- Our users may also want to call `vTaskSetThreadLocalStoragePointer()` in their own applications, thus we need to reserve a hidden set of TLSPs that are not exposed to the users.

Having some TCB storage that is completely hidden from users and requires no additional user action would be ideal for us.

**Comment by aggarg** [comment]
> Requiring each task to initialize/deinitialize TLSPs will a difficult requirement to propagate. 

You should be able to use [portSETUP_TCB](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/tasks.c#L1101) and [portCLEAN_UP_TCB](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/tasks.c#L3960) for init and de-init purpose?

**Comment by Dazza0** [comment]
@aggarg The issue with regards to the TLSPs is that our users also make use of the TLSPs. So in order to not allow users to access the port TLSPs,, we will need to have reserved entries in `TCB.pvThreadLocalStoragePointers`.

However, in the end we've gone with a different approach. The pointers to the FPU/Coprocessor save areas are now calculated at run time whenever they are used, thus we no longer need to store any port specific data in the TCBs. Thanks for the review.

**Comment by aggarg** [comment]
Thank you.

**Pull request closed without merging**
