### PR TITLE
Add ePendingReady state for task in a pending ready list

### PR DESCRIPTION
**Pull request by chinglee-iot**
Add ePendingReady state.
The unit test is updated in another PR.

Description
-----------
* Add ePendingReady state for task in a pending ready list.

Test Steps
-----------
Run the unit test case [test_eTaskGetState_success_not_current_tcb_pending_ready](https://github.com/FreeRTOS/FreeRTOS/blob/8f3233e0a0730b16f4fed3669d89954cbdd39ea2/FreeRTOS/Test/CMock/tasks/tasks_1_utest.c#L1724).
* Before this PR, eReady is expected.
* After this PR, ePendingReady should be expected.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jefftenney** [comment]
>If a blocked or suspended task is readied by an ISR while the running task suspends the scheduler, the task's state will still be eBlocked or eSuspended with current logic.

@chinglee-iot It seems this issue was recently addressed in #679.  After that PR, the above statement is no longer true.  After #679, the new behavior is: "If a blocked or suspended task is readied by an ISR while the running task suspends the scheduler, the task's state will be eReady."

Is there a benefit to distinguishing `ePendingReady` from `eReady` in the API?  The pending-ready status is a scheduler implementation detail not currently exposed to the API.  From the user's perspective, maybe a task in the pending-ready list really is `eReady`.

**Comment by RichardBarry** [comment]
Reading Jeff's comment, I agree it could be confusing to expose internal implementation detail.  The PR is responding to this scenario: https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/577, so the question is, is that a valid scenario.  Is it valid to call eTaskGetState() when the scheduler is suspended when the generalised rule of thumb is not to call API functions from a critical section or with the scheduler suspended.

The head revision already returns eReady for this scenario.

**Comment by chinglee-iot** [comment]
Agreed with Jeff's and Richard's comment. Let's close this PR and create another for minor update with eReady comment.

**Comment by jefftenney** [comment]
@chinglee-iot Prior to #679, `eTaskGetState()` would return `eBlocked` or `eSuspended` under the conditions being discussed.  After #679, it returns `eReady`.  However, #679 did *not* make the corresponding change to `uxTaskGetSystemState()`, which still returns `eBlocked` or `eSuspended`.  Thus #679 introduced a minor inconsistency.  Addressing that inconsistency would probably make a good PR.

In my opinion returning `eReady` is ideal behavior, even considering that a developer making this API call with the scheduler suspended is suspect, as Richard says.  So I think changing `uxTaskGetSystemState()` to match the current `eTaskGetState()` behavior is best.

**Comment by chinglee-iot** [comment]
@jefftenney I will create another PR for the uxTaskGetSystemState() function. Let's discuss in the new PR.

**Comment by chinglee-iot** [comment]
We created another PR for uxTaskGetSystemState() function. #702

**Pull request closed without merging**
